export interface CheatCommand {
  cmd: string;
  desc: string;
  /** Marks commands that mutate/destroy state (drop, kill, delete, force-push, ...). */
  danger?: boolean;
}

export interface CheatGroup {
  id: string;
  label: string;
  commands: CheatCommand[];
}

export const COMMAND_GROUPS: CheatGroup[] = [
  {
    id: "git",
    label: "Git / Git Bash",
    commands: [
      { cmd: "git status", desc: "Show changed, staged and untracked files" },
      { cmd: "git log --oneline --graph --all", desc: "Compact commit graph across all branches" },
      { cmd: "git diff", desc: "Show unstaged changes" },
      { cmd: "git diff --staged", desc: "Show staged changes" },
      { cmd: "git add -p", desc: "Interactively stage hunks" },
      { cmd: "git commit -m \"message\"", desc: "Commit staged changes" },
      { cmd: "git checkout -b feature/x", desc: "Create and switch to a new branch" },
      { cmd: "git switch -c feature/x", desc: "Same as above, newer syntax" },
      { cmd: "git stash -u", desc: "Stash tracked + untracked changes" },
      { cmd: "git stash pop", desc: "Reapply the most recent stash" },
      { cmd: "git rebase -i HEAD~5", desc: "Interactively rebase the last 5 commits" },
      { cmd: "git reset --soft HEAD~1", desc: "Undo last commit, keep changes staged" },
      { cmd: "git reset --hard HEAD~1", desc: "Undo last commit and discard changes", danger: true },
      { cmd: "git clean -fd", desc: "Delete untracked files and directories", danger: true },
      { cmd: "git push --force-with-lease", desc: "Force-push safely (fails if remote has new commits)", danger: true },
      { cmd: "git fetch --all --prune", desc: "Fetch all remotes and remove stale remote branches" },
      { cmd: "git blame -L 10,20 file", desc: "Show who last changed lines 10-20 of a file" },
      { cmd: "git bisect start", desc: "Begin binary search for the commit that introduced a bug" },
      { cmd: "git worktree add ../wt-branch branch", desc: "Check out a branch into a separate directory" },
      { cmd: "git remote -v", desc: "List remotes and their URLs" },
    ],
  },
  {
    id: "ssh",
    label: "SSH / PuTTY",
    commands: [
      { cmd: "ssh user@host", desc: "Connect to a remote host" },
      { cmd: "ssh -i keyfile.pem user@host", desc: "Connect using a private key" },
      { cmd: "ssh -p 2222 user@host", desc: "Connect on a non-default port" },
      { cmd: "ssh -L 8080:localhost:80 user@host", desc: "Local port forward: localhost:8080 -> remote:80" },
      { cmd: "ssh -D 1080 user@host", desc: "Open a SOCKS5 proxy tunnelled through the host" },
      { cmd: "scp file.txt user@host:/remote/path/", desc: "Copy a local file to a remote host" },
      { cmd: "scp -r user@host:/remote/dir ./local", desc: "Copy a remote directory to local, recursively" },
      { cmd: "ssh-keygen -t ed25519 -C \"you@example.com\"", desc: "Generate a new SSH keypair" },
      { cmd: "ssh-copy-id user@host", desc: "Install your public key on a remote host" },
      { cmd: "puttygen key.ppk -O private-openssh -o key.pem", desc: "Convert a PuTTY .ppk key to OpenSSH format" },
      { cmd: "pscp file.txt user@host:/remote/path/", desc: "PuTTY's scp equivalent (Windows)" },
      { cmd: "plink user@host -i key.ppk \"uptime\"", desc: "Run a single remote command via PuTTY's plink" },
    ],
  },
  {
    id: "linux",
    label: "Linux",
    commands: [
      { cmd: "ls -lah", desc: "List files with details, including hidden" },
      { cmd: "df -h", desc: "Disk space usage, human-readable" },
      { cmd: "du -sh * | sort -h", desc: "Size of each item in current dir, sorted" },
      { cmd: "top", desc: "Live process/resource monitor" },
      { cmd: "htop", desc: "Nicer interactive process monitor" },
      { cmd: "ps aux | grep name", desc: "Find processes matching a name" },
      { cmd: "kill -9 pid", desc: "Force-kill a process by PID", danger: true },
      { cmd: "chmod +x script.sh", desc: "Make a file executable" },
      { cmd: "chown user:group file", desc: "Change file owner and group" },
      { cmd: "tail -f /var/log/syslog", desc: "Follow a log file live" },
      { cmd: "grep -rn \"text\" .", desc: "Recursively search for text, show line numbers" },
      { cmd: "find . -name \"*.log\" -mtime +7", desc: "Find files older than 7 days" },
      { cmd: "tar -czvf out.tar.gz dir/", desc: "Compress a directory to .tar.gz" },
      { cmd: "tar -xzvf out.tar.gz", desc: "Extract a .tar.gz archive" },
      { cmd: "systemctl status service", desc: "Show status of a systemd service" },
      { cmd: "systemctl restart service", desc: "Restart a systemd service" },
      { cmd: "journalctl -u service -f", desc: "Follow logs for a systemd service" },
      { cmd: "rm -rf dir/", desc: "Recursively delete a directory, no confirmation", danger: true },
      { cmd: "crontab -e", desc: "Edit the current user's cron schedule" },
      { cmd: "history | grep cmd", desc: "Search shell command history" },
    ],
  },
  {
    id: "windows",
    label: "Windows / Daily System",
    commands: [
      { cmd: "Get-Process | Sort-Object CPU -Descending | Select -First 10", desc: "Top 10 processes by CPU (PowerShell)" },
      { cmd: "Get-Service | Where-Object Status -eq Running", desc: "List running Windows services" },
      { cmd: "taskkill /PID 1234 /F", desc: "Force-kill a process by PID", danger: true },
      { cmd: "tasklist | findstr name", desc: "Find a running process by name" },
      { cmd: "netstat -ano | findstr :8080", desc: "Find the process listening on port 8080" },
      { cmd: "ipconfig /all", desc: "Show all network adapter configuration" },
      { cmd: "ipconfig /flushdns", desc: "Clear the local DNS resolver cache" },
      { cmd: "Get-ChildItem -Recurse -Filter *.log", desc: "Find files recursively by extension (PowerShell)" },
      { cmd: "Compress-Archive -Path dir -DestinationPath out.zip", desc: "Zip a folder (PowerShell)" },
      { cmd: "shutdown /r /t 0", desc: "Restart immediately", danger: true },
      { cmd: "sfc /scannow", desc: "Scan and repair protected system files" },
      { cmd: "wmic os get Caption,Version,BuildNumber", desc: "Show Windows edition/version/build" },
      { cmd: "reg query HKLM\\Software", desc: "Query the registry (read-only browse)" },
      { cmd: "schtasks /query /fo LIST /v", desc: "List scheduled tasks with details" },
      { cmd: "Get-EventLog -LogName System -Newest 20", desc: "Show the 20 newest System event log entries" },
    ],
  },
  {
    id: "mssql",
    label: "MSSQL",
    commands: [
      { cmd: "sqlcmd -S server -U user -P password -d dbname", desc: "Connect to a SQL Server instance" },
      { cmd: "sqlcmd -S server -E -Q \"SELECT @@VERSION\"", desc: "Run a single query with Windows auth" },
      { cmd: "SELECT name FROM sys.databases;", desc: "List all databases on the server" },
      { cmd: "SELECT * FROM sys.tables ORDER BY name;", desc: "List all tables in the current database" },
      { cmd: "sp_helpdb dbname", desc: "Show database file layout and size info" },
      { cmd: "sp_who2", desc: "Show active connections/sessions and blocking" },
      { cmd: "BACKUP DATABASE db TO DISK='C:\\backup\\db.bak';", desc: "Back up a database to disk" },
      { cmd: "RESTORE DATABASE db FROM DISK='C:\\backup\\db.bak' WITH REPLACE;", desc: "Restore a database from a backup file", danger: true },
      { cmd: "DBCC CHECKDB('dbname');", desc: "Check database integrity" },
      { cmd: "DROP DATABASE dbname;", desc: "Permanently delete a database", danger: true },
      { cmd: "EXEC sp_rename 'old_table', 'new_table';", desc: "Rename a table" },
      { cmd: "SELECT * FROM sys.dm_exec_requests WHERE blocking_session_id != 0;", desc: "Show currently blocked queries" },
    ],
  },
  {
    id: "pgsql",
    label: "PostgreSQL",
    commands: [
      { cmd: "psql -U user -d dbname -h host", desc: "Connect to a Postgres database" },
      { cmd: "\\l", desc: "List all databases (inside psql)" },
      { cmd: "\\dt", desc: "List tables in the current schema (inside psql)" },
      { cmd: "\\d tablename", desc: "Describe a table's columns/indexes (inside psql)" },
      { cmd: "\\du", desc: "List roles/users (inside psql)" },
      { cmd: "pg_dump -U user dbname > backup.sql", desc: "Dump a database to a SQL file" },
      { cmd: "psql -U user dbname < backup.sql", desc: "Restore a database from a SQL dump" },
      { cmd: "SELECT * FROM pg_stat_activity;", desc: "Show current connections and running queries" },
      { cmd: "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid = 1234;", desc: "Kill a specific backend/connection", danger: true },
      { cmd: "VACUUM ANALYZE tablename;", desc: "Reclaim space and update planner statistics for a table" },
      { cmd: "DROP DATABASE dbname;", desc: "Permanently delete a database", danger: true },
      { cmd: "EXPLAIN ANALYZE SELECT ...;", desc: "Show the query plan with actual execution timing" },
      { cmd: "pg_isready -h host -p 5432", desc: "Check if a Postgres server is accepting connections" },
    ],
  },
  {
    id: "redis",
    label: "Redis",
    commands: [
      { cmd: "redis-cli -h host -p 6379", desc: "Connect to a Redis server" },
      { cmd: "redis-cli -a password PING", desc: "Check server is alive (with auth)" },
      { cmd: "KEYS *", desc: "List all keys (avoid in production, blocks the server)" },
      { cmd: "SCAN 0 MATCH pattern:* COUNT 100", desc: "Iterate keys matching a pattern without blocking" },
      { cmd: "GET key", desc: "Get the value of a string key" },
      { cmd: "TTL key", desc: "Show remaining time-to-live of a key in seconds" },
      { cmd: "EXPIRE key 3600", desc: "Set a key to expire in 3600 seconds" },
      { cmd: "DEL key", desc: "Delete a key", danger: true },
      { cmd: "FLUSHDB", desc: "Delete all keys in the current database", danger: true },
      { cmd: "FLUSHALL", desc: "Delete all keys in all databases", danger: true },
      { cmd: "INFO", desc: "Show server stats: memory, clients, replication, etc" },
      { cmd: "MONITOR", desc: "Stream every command processed by the server, live" },
      { cmd: "CONFIG GET maxmemory", desc: "Read a server config value" },
      { cmd: "redis-cli --bigkeys", desc: "Sample keyspace to find the largest keys" },
    ],
  },
  {
    id: "nats",
    label: "NATS",
    commands: [
      { cmd: "nats server check connection --server=host:4222", desc: "Check connectivity to a NATS server" },
      { cmd: "nats sub \"subject.>\"", desc: "Subscribe and print messages on a subject wildcard" },
      { cmd: "nats pub subject \"payload\"", desc: "Publish a message to a subject" },
      { cmd: "nats req subject \"payload\"", desc: "Send a request and wait for a reply" },
      { cmd: "nats stream ls", desc: "List JetStream streams" },
      { cmd: "nats stream info STREAM", desc: "Show config/state of a JetStream stream" },
      { cmd: "nats consumer ls STREAM", desc: "List consumers on a stream" },
      { cmd: "nats stream purge STREAM", desc: "Delete all messages in a stream", danger: true },
      { cmd: "nats server report jetstream", desc: "Cluster-wide JetStream usage report" },
      { cmd: "nats-server -c nats-server.conf", desc: "Start a NATS server with a config file" },
    ],
  },
  {
    id: "curl",
    label: "cURL",
    commands: [
      { cmd: "curl -i https://api.example.com/health", desc: "GET request, show response headers" },
      { cmd: "curl -X POST -H \"Content-Type: application/json\" -d '{\"a\":1}' https://api.example.com", desc: "POST JSON body" },
      { cmd: "curl -H \"Authorization: Bearer TOKEN\" https://api.example.com", desc: "Send a bearer token auth header" },
      { cmd: "curl -o file.zip https://example.com/file.zip", desc: "Download a file to disk" },
      { cmd: "curl -L https://short.url", desc: "Follow redirects" },
      { cmd: "curl -v https://api.example.com", desc: "Verbose output including TLS handshake and headers" },
      { cmd: "curl -k https://self-signed.local", desc: "Skip TLS certificate verification (dev only)" },
      { cmd: "curl -w \"%{time_total}\\n\" -o /dev/null -s https://api.example.com", desc: "Print only the total request time" },
      { cmd: "curl -u user:pass https://api.example.com", desc: "Basic auth" },
      { cmd: "curl --data-urlencode \"q=hello world\" https://api.example.com/search", desc: "URL-encode a query parameter" },
    ],
  },
  {
    id: "network",
    label: "Network",
    commands: [
      { cmd: "ping host", desc: "Check reachability and round-trip latency" },
      { cmd: "traceroute host", desc: "Show the route packets take to a host (Linux/macOS)" },
      { cmd: "tracert host", desc: "Same as above on Windows" },
      { cmd: "nslookup host", desc: "Resolve a hostname's DNS records" },
      { cmd: "dig host +short", desc: "Concise DNS lookup" },
      { cmd: "dig -x 1.2.3.4", desc: "Reverse DNS lookup for an IP" },
      { cmd: "nc -zv host 443", desc: "Test if a TCP port is open" },
      { cmd: "telnet host 23", desc: "Open a raw TCP connection to test a port interactively" },
      { cmd: "netstat -tulpn", desc: "List listening ports and owning processes (Linux)" },
      { cmd: "whois domain.com", desc: "Look up domain registration info" },
      { cmd: "curl ifconfig.me", desc: "Show your public IP address" },
      { cmd: "arp -a", desc: "Show the local ARP table" },
    ],
  },
  {
    id: "dotnet",
    label: ".NET CLI",
    commands: [
      { cmd: "dotnet new webapi -n MyApi", desc: "Scaffold a new Web API project" },
      { cmd: "dotnet build", desc: "Build the project/solution" },
      { cmd: "dotnet run", desc: "Build and run the project" },
      { cmd: "dotnet watch run", desc: "Run with hot-reload on file changes" },
      { cmd: "dotnet test", desc: "Run unit tests" },
      { cmd: "dotnet publish -c Release -o out", desc: "Publish a release build to a folder" },
      { cmd: "dotnet ef migrations add InitName", desc: "Add a new EF Core migration" },
      { cmd: "dotnet ef database update", desc: "Apply pending EF Core migrations to the database" },
      { cmd: "dotnet add package PackageName", desc: "Add a NuGet package reference" },
      { cmd: "dotnet restore", desc: "Restore NuGet dependencies" },
      { cmd: "dotnet nuget locals all --clear", desc: "Clear all local NuGet caches" },
      { cmd: "dotnet --list-sdks", desc: "List installed .NET SDK versions" },
    ],
  },
  {
    id: "npm",
    label: "NPM / Node",
    commands: [
      { cmd: "npm install", desc: "Install dependencies from package.json/lockfile" },
      { cmd: "npm ci", desc: "Clean install exactly matching the lockfile (CI-safe)" },
      { cmd: "npm run dev", desc: "Run the \"dev\" script" },
      { cmd: "npm outdated", desc: "List installed packages with newer versions available" },
      { cmd: "npm update package", desc: "Update a package within its semver range" },
      { cmd: "npm uninstall package", desc: "Remove a package" },
      { cmd: "npm audit fix", desc: "Attempt to auto-fix known vulnerabilities" },
      { cmd: "npx package-name", desc: "Run a package's CLI without installing it globally" },
      { cmd: "npm list --depth=0", desc: "Show top-level installed dependencies" },
      { cmd: "npm cache clean --force", desc: "Clear the local npm cache" },
      { cmd: "node --version", desc: "Show the installed Node.js version" },
      { cmd: "nvm use 20", desc: "Switch active Node version (with nvm installed)" },
    ],
  },
];
