export interface CheatCommand {
  cmd: string;
  desc: string;
  /** Usage-type bucket used to group commands within a tab, e.g. "Branch & Switch". */
  type: string;
  /** Marks commands that mutate/destroy state (drop, kill, delete, force-push, ...). */
  danger?: boolean;
}

export interface CheatGroup {
  id: string;
  label: string;
  commands: CheatCommand[];
}

export const COMMAND_GROUPS: CheatGroup[] = [
  {
    id: "git",
    label: "Git / Git Bash",
    commands: [
      { cmd: "git status", desc: "Show changed, staged and untracked files", type: "Inspect" },
      { cmd: "git diff", desc: "Show unstaged changes", type: "Inspect" },
      { cmd: "git diff --staged", desc: "Show staged changes", type: "Inspect" },
      { cmd: "git diff branchA..branchB", desc: "Show changes between two branches", type: "Inspect" },
      { cmd: "git log --oneline --graph --all", desc: "Compact commit graph across all branches", type: "Inspect" },
      { cmd: "git log -p -- file", desc: "Show full patch history for a single file", type: "Inspect" },
      { cmd: "git show commitHash", desc: "Show the changes introduced by one commit", type: "Inspect" },
      { cmd: "git blame -L 10,20 file", desc: "Show who last changed lines 10-20 of a file", type: "Inspect" },
      { cmd: "git check-ignore -v file", desc: "Show which .gitignore rule is excluding a file", type: "Inspect" },
      { cmd: "git remote -v", desc: "List remotes and their URLs", type: "Inspect" },
      { cmd: "git add -p", desc: "Interactively stage hunks", type: "Stage & Commit" },
      { cmd: "git commit -m \"message\"", desc: "Commit staged changes", type: "Stage & Commit" },
      { cmd: "git commit --amend --no-edit", desc: "Add staged changes to the previous commit, keep its message", type: "Stage & Commit" },
      { cmd: "git checkout -b feature/x", desc: "Create and switch to a new branch", type: "Branch & Switch" },
      { cmd: "git switch -c feature/x", desc: "Same as above, newer syntax", type: "Branch & Switch" },
      { cmd: "git branch -d feature/x", desc: "Delete a local branch (only if merged)", type: "Branch & Switch" },
      { cmd: "git branch -D feature/x", desc: "Force-delete a local branch, merged or not", type: "Branch & Switch", danger: true },
      { cmd: "git worktree add ../wt-branch branch", desc: "Check out a branch into a separate directory", type: "Branch & Switch" },
      { cmd: "git merge --no-ff feature/x", desc: "Merge a branch, always creating a merge commit", type: "Branch & Switch" },
      { cmd: "git tag -a v1.2.0 -m \"release\"", desc: "Create an annotated tag", type: "Tags & Snapshots" },
      { cmd: "git push origin v1.2.0", desc: "Push a single tag to the remote", type: "Tags & Snapshots" },
      { cmd: "git archive --format=zip -o out.zip HEAD", desc: "Export the repo at a ref as a zip, no .git folder", type: "Tags & Snapshots" },
      { cmd: "git stash -u", desc: "Stash tracked + untracked changes", type: "Stash" },
      { cmd: "git stash pop", desc: "Reapply the most recent stash", type: "Stash" },
      { cmd: "git stash list", desc: "List all stashed changesets", type: "Stash" },
      { cmd: "git cherry-pick commitHash", desc: "Apply a single commit from another branch onto the current one", type: "History & Rewrite" },
      { cmd: "git revert commitHash", desc: "Create a new commit that undoes a previous commit, safe on shared history", type: "History & Rewrite" },
      { cmd: "git rebase -i HEAD~5", desc: "Interactively rebase the last 5 commits", type: "History & Rewrite" },
      { cmd: "git reset --soft HEAD~1", desc: "Undo last commit, keep changes staged", type: "History & Rewrite" },
      { cmd: "git reset --hard HEAD~1", desc: "Undo last commit and discard changes", type: "History & Rewrite", danger: true },
      { cmd: "git clean -fd", desc: "Delete untracked files and directories", type: "History & Rewrite", danger: true },
      { cmd: "git reflog", desc: "Show every ref update, the safety net for recovering lost commits", type: "History & Rewrite" },
      { cmd: "git bisect start", desc: "Begin binary search for the commit that introduced a bug", type: "History & Rewrite" },
      { cmd: "git submodule update --init --recursive", desc: "Clone/update all submodules referenced by the repo", type: "Submodules" },
      { cmd: "git fetch --all --prune", desc: "Fetch all remotes and remove stale remote branches", type: "Remote & Sync" },
      { cmd: "git push --force-with-lease", desc: "Force-push safely (fails if remote has new commits)", type: "Remote & Sync", danger: true },
      { cmd: "git pull --rebase", desc: "Fetch and replay local commits on top instead of merging", type: "Remote & Sync" },
    ],
  },
  {
    id: "ssh",
    label: "SSH / PuTTY",
    commands: [
      { cmd: "ssh user@host", desc: "Connect to a remote host", type: "Connect" },
      { cmd: "ssh -i keyfile.pem user@host", desc: "Connect using a private key", type: "Connect" },
      { cmd: "ssh -p 2222 user@host", desc: "Connect on a non-default port", type: "Connect" },
      { cmd: "ssh -J jumpuser@bastion user@host", desc: "Connect through a bastion/jump host", type: "Connect" },
      { cmd: "plink user@host -i key.ppk \"uptime\"", desc: "Run a single remote command via PuTTY's plink", type: "Connect" },
      { cmd: "sftp user@host", desc: "Open an interactive SFTP session", type: "Connect" },
      { cmd: "scp file.txt user@host:/remote/path/", desc: "Copy a local file to a remote host", type: "File Transfer" },
      { cmd: "scp -r user@host:/remote/dir ./local", desc: "Copy a remote directory to local, recursively", type: "File Transfer" },
      { cmd: "pscp file.txt user@host:/remote/path/", desc: "PuTTY's scp equivalent (Windows)", type: "File Transfer" },
      { cmd: "rsync -avz --progress ./local/ user@host:/remote/", desc: "Sync a local directory to remote, only transferring changes", type: "File Transfer" },
      { cmd: "rsync -avz -e \"ssh -p 2222\" ./local/ user@host:/remote/", desc: "Rsync over SSH on a custom port", type: "File Transfer" },
      { cmd: "sshfs user@host:/remote/path /mnt/point", desc: "Mount a remote directory locally over SSH", type: "File Transfer" },
      { cmd: "ssh -L 8080:localhost:80 user@host", desc: "Local port forward: localhost:8080 -> remote:80", type: "Tunneling" },
      { cmd: "ssh -R 9000:localhost:3000 user@host", desc: "Remote port forward: expose local:3000 on the remote host", type: "Tunneling" },
      { cmd: "ssh -D 1080 user@host", desc: "Open a SOCKS5 proxy tunnelled through the host", type: "Tunneling" },
      { cmd: "ssh -O check -S ~/.ssh/cm-%r@%h:%p user@host", desc: "Check if an SSH ControlMaster (multiplexed) connection is active", type: "Tunneling" },
      { cmd: "ssh-keygen -t ed25519 -C \"you@example.com\"", desc: "Generate a new SSH keypair", type: "Keys" },
      { cmd: "ssh-copy-id user@host", desc: "Install your public key on a remote host", type: "Keys" },
      { cmd: "puttygen key.ppk -O private-openssh -o key.pem", desc: "Convert a PuTTY .ppk key to OpenSSH format", type: "Keys" },
      { cmd: "ssh-add ~/.ssh/id_ed25519", desc: "Add a key to the running ssh-agent so you're not re-prompted", type: "Keys" },
    ],
  },
  {
    id: "linux",
    label: "Linux",
    commands: [
      { cmd: "ls -lah", desc: "List files with details, including hidden", type: "Files & Disk" },
      { cmd: "df -h", desc: "Disk space usage, human-readable", type: "Files & Disk" },
      { cmd: "du -sh * | sort -h", desc: "Size of each item in current dir, sorted", type: "Files & Disk" },
      { cmd: "lsblk", desc: "List block devices/partitions and mount points", type: "Files & Disk" },
      { cmd: "mount /dev/sdb1 /mnt/data", desc: "Mount a device to a directory", type: "Files & Disk" },
      { cmd: "cp -r src/ dest/", desc: "Copy a directory and its contents recursively", type: "Copy & Move" },
      { cmd: "cp -a src/ dest/", desc: "Copy preserving permissions, ownership and timestamps", type: "Copy & Move" },
      { cmd: "mv oldname newname", desc: "Move or rename a file/directory", type: "Copy & Move" },
      { cmd: "ln -s /path/to/target linkname", desc: "Create a symbolic link", type: "Copy & Move" },
      { cmd: "rsync -av --delete src/ dest/", desc: "Mirror a directory locally, deleting extras at destination", type: "Copy & Move" },
      { cmd: "mkdir -p a/b/c", desc: "Create nested directories in one go", type: "Copy & Move" },
      { cmd: "rm -rf dir/", desc: "Recursively delete a directory, no confirmation", type: "Copy & Move", danger: true },
      { cmd: "chmod +x script.sh", desc: "Make a file executable", type: "Permissions" },
      { cmd: "chmod 750 file", desc: "Set exact rwx permissions for owner/group/others", type: "Permissions" },
      { cmd: "chown -R user:group dir/", desc: "Change owner and group recursively", type: "Permissions" },
      { cmd: "useradd -m newuser", desc: "Create a new user with a home directory", type: "Permissions" },
      { cmd: "passwd username", desc: "Set or change a user's password", type: "Permissions" },
      { cmd: "top", desc: "Live process/resource monitor", type: "Process & Monitor" },
      { cmd: "htop", desc: "Nicer interactive process monitor", type: "Process & Monitor" },
      { cmd: "ps aux | grep name", desc: "Find processes matching a name", type: "Process & Monitor" },
      { cmd: "kill -9 pid", desc: "Force-kill a process by PID", type: "Process & Monitor", danger: true },
      { cmd: "nohup ./run.sh &", desc: "Run a command in the background, immune to hangup on logout", type: "Process & Monitor" },
      { cmd: "grep -rn \"text\" .", desc: "Recursively search for text, show line numbers", type: "Search & Text" },
      { cmd: "find . -name \"*.log\" -mtime +7", desc: "Find files older than 7 days", type: "Search & Text" },
      { cmd: "find . -size +100M", desc: "Find files larger than 100MB", type: "Search & Text" },
      { cmd: "sed -i 's/old/new/g' file", desc: "In-place find-and-replace across a file", type: "Search & Text" },
      { cmd: "awk -F, '{print $2}' file.csv", desc: "Print the second comma-separated column of every line", type: "Search & Text" },
      { cmd: "sort file.txt | uniq -c | sort -nr", desc: "Count and rank duplicate lines, most frequent first", type: "Search & Text" },
      { cmd: "xargs -I{} rm {} < files.txt", desc: "Run a command once per line read from input", type: "Search & Text" },
      { cmd: "history | grep cmd", desc: "Search shell command history", type: "Search & Text" },
      { cmd: "md5sum file", desc: "Compute an MD5 checksum, useful to verify file integrity", type: "Search & Text" },
      { cmd: "sha256sum file", desc: "Compute a SHA-256 checksum", type: "Search & Text" },
      { cmd: "tar -czvf out.tar.gz dir/", desc: "Compress a directory to .tar.gz", type: "Archive" },
      { cmd: "tar -xzvf out.tar.gz", desc: "Extract a .tar.gz archive", type: "Archive" },
      { cmd: "zip -r out.zip dir/", desc: "Compress a directory into a .zip", type: "Archive" },
      { cmd: "unzip out.zip -d dest/", desc: "Extract a .zip into a target directory", type: "Archive" },
      { cmd: "tail -f /var/log/syslog", desc: "Follow a log file live", type: "Service" },
      { cmd: "systemctl status service", desc: "Show status of a systemd service", type: "Service" },
      { cmd: "systemctl restart service", desc: "Restart a systemd service", type: "Service" },
      { cmd: "systemctl enable service", desc: "Start a service automatically on boot", type: "Service" },
      { cmd: "journalctl -u service -f", desc: "Follow logs for a systemd service", type: "Service" },
      { cmd: "ip a", desc: "Show all network interfaces and their IP addresses", type: "Network" },
      { cmd: "ss -tulpn", desc: "List listening TCP/UDP ports and owning processes", type: "Network" },
      { cmd: "apt install pkg", desc: "Install a package (Debian/Ubuntu)", type: "Package Manager" },
      { cmd: "apt update && apt upgrade -y", desc: "Refresh package index and upgrade everything", type: "Package Manager" },
      { cmd: "crontab -e", desc: "Edit the current user's cron schedule", type: "Scheduling" },
    ],
  },
  {
    id: "windows",
    label: "Windows / Daily System",
    commands: [
      { cmd: "Copy-Item src.txt dest.txt", desc: "Copy a file (PowerShell)", type: "Copy & Move" },
      { cmd: "Copy-Item src/ dest/ -Recurse", desc: "Copy a directory recursively (PowerShell)", type: "Copy & Move" },
      { cmd: "Move-Item src.txt dest\\", desc: "Move a file to another folder (PowerShell)", type: "Copy & Move" },
      { cmd: "Rename-Item old.txt new.txt", desc: "Rename a file (PowerShell)", type: "Copy & Move" },
      { cmd: "robocopy src dest /MIR /R:3", desc: "Mirror a directory tree, retry 3x on locked files", type: "Copy & Move" },
      { cmd: "xcopy src dest /E /I /Y", desc: "Copy a directory tree including empty folders, no prompts", type: "Copy & Move" },
      { cmd: "New-Item -ItemType Directory -Path a\\b\\c -Force", desc: "Create nested directories in one go", type: "Copy & Move" },
      { cmd: "Remove-Item dir -Recurse -Force", desc: "Recursively delete a directory, no confirmation", type: "Copy & Move", danger: true },
      { cmd: "Get-Process | Sort-Object CPU -Descending | Select -First 10", desc: "Top 10 processes by CPU (PowerShell)", type: "Process" },
      { cmd: "tasklist | findstr name", desc: "Find a running process by name", type: "Process" },
      { cmd: "taskkill /PID 1234 /F", desc: "Force-kill a process by PID", type: "Process", danger: true },
      { cmd: "Get-Service | Where-Object Status -eq Running", desc: "List running Windows services", type: "Process" },
      { cmd: "Start-Service serviceName", desc: "Start a Windows service", type: "Process" },
      { cmd: "Stop-Service serviceName -Force", desc: "Stop a Windows service", type: "Process", danger: true },
      { cmd: "netstat -ano | findstr :8080", desc: "Find the process listening on port 8080", type: "Network" },
      { cmd: "Test-NetConnection host -Port 443", desc: "Check TCP connectivity to a host/port (PowerShell)", type: "Network" },
      { cmd: "Get-NetTCPConnection -State Listen", desc: "List all ports currently in a listening state", type: "Network" },
      { cmd: "ipconfig /all", desc: "Show all network adapter configuration", type: "Network" },
      { cmd: "ipconfig /flushdns", desc: "Clear the local DNS resolver cache", type: "Network" },
      { cmd: "Get-ChildItem -Recurse -Filter *.log", desc: "Find files recursively by extension (PowerShell)", type: "Files" },
      { cmd: "Select-String -Path *.log -Pattern \"error\"", desc: "Search file contents for a pattern, like grep", type: "Files" },
      { cmd: "Get-FileHash file -Algorithm SHA256", desc: "Compute a file's checksum (PowerShell)", type: "Files" },
      { cmd: "Compress-Archive -Path dir -DestinationPath out.zip", desc: "Zip a folder (PowerShell)", type: "Files" },
      { cmd: "Expand-Archive out.zip -DestinationPath dest\\", desc: "Unzip an archive (PowerShell)", type: "Files" },
      { cmd: "sfc /scannow", desc: "Scan and repair protected system files", type: "System" },
      { cmd: "wmic os get Caption,Version,BuildNumber", desc: "Show Windows edition/version/build", type: "System" },
      { cmd: "Get-PSDrive -PSProvider FileSystem", desc: "Show drive letters and free/used space", type: "System" },
      { cmd: "$env:PATH -split ';'", desc: "Print the PATH environment variable, one entry per line", type: "System" },
      { cmd: "wsl --list --verbose", desc: "List installed WSL distros and their versions", type: "System" },
      { cmd: "shutdown /r /t 0", desc: "Restart immediately", type: "System", danger: true },
      { cmd: "reg query HKLM\\Software", desc: "Query the registry (read-only browse)", type: "Registry & Tasks" },
      { cmd: "schtasks /query /fo LIST /v", desc: "List scheduled tasks with details", type: "Registry & Tasks" },
      { cmd: "Get-EventLog -LogName System -Newest 20", desc: "Show the 20 newest System event log entries", type: "Logs" },
    ],
  },
  {
    id: "mssql",
    label: "MSSQL",
    commands: [
      { cmd: "sqlcmd -S server -U user -P password -d dbname", desc: "Connect to a SQL Server instance", type: "Connect" },
      { cmd: "sqlcmd -S server -E -Q \"SELECT @@VERSION\"", desc: "Run a single query with Windows auth", type: "Connect" },
      { cmd: "SELECT name FROM sys.databases;", desc: "List all databases on the server", type: "Explore" },
      { cmd: "SELECT * FROM sys.tables ORDER BY name;", desc: "List all tables in the current database", type: "Explore" },
      { cmd: "sp_helpdb dbname", desc: "Show database file layout and size info", type: "Explore" },
      { cmd: "sp_helptext 'dbo.MyProc'", desc: "Show the definition/source of a stored procedure", type: "Explore" },
      { cmd: "EXEC sp_rename 'old_table', 'new_table';", desc: "Rename a table", type: "Explore" },
      { cmd: "SELECT * INTO new_table FROM old_table;", desc: "Copy a table's structure and data into a new table", type: "Copy & Move" },
      { cmd: "bcp dbo.Table out data.csv -S server -T -c -t,", desc: "Export a table to a CSV file", type: "Copy & Move" },
      { cmd: "bcp dbo.Table in data.csv -S server -T -c -t,", desc: "Bulk-import a CSV file into a table", type: "Copy & Move" },
      { cmd: "CREATE INDEX IX_Table_Col ON Table(Col);", desc: "Add a non-clustered index to speed up lookups", type: "Schema" },
      { cmd: "ALTER TABLE Table ADD Col INT NULL;", desc: "Add a new nullable column to a table", type: "Schema" },
      { cmd: "GRANT SELECT ON Table TO username;", desc: "Grant read access on a table to a user", type: "Schema" },
      { cmd: "sp_who2", desc: "Show active connections/sessions and blocking", type: "Session & Locks" },
      { cmd: "SELECT * FROM sys.dm_exec_requests WHERE blocking_session_id != 0;", desc: "Show currently blocked queries", type: "Session & Locks" },
      { cmd: "KILL 55;", desc: "Terminate a session by its SPID", type: "Session & Locks", danger: true },
      { cmd: "BACKUP DATABASE db TO DISK='C:\\backup\\db.bak';", desc: "Back up a database to disk", type: "Backup & Restore" },
      { cmd: "RESTORE DATABASE db FROM DISK='C:\\backup\\db.bak' WITH REPLACE;", desc: "Restore a database from a backup file", type: "Backup & Restore", danger: true },
      { cmd: "DBCC CHECKDB('dbname');", desc: "Check database integrity", type: "Maintenance" },
      { cmd: "DBCC SHRINKDATABASE(dbname);", desc: "Shrink a database's data/log files to reclaim disk space", type: "Maintenance" },
      { cmd: "TRUNCATE TABLE Table;", desc: "Remove all rows from a table instantly, cannot be rolled back after commit", type: "Maintenance", danger: true },
      { cmd: "DROP DATABASE dbname;", desc: "Permanently delete a database", type: "Maintenance", danger: true },
    ],
  },
  {
    id: "pgsql",
    label: "PostgreSQL",
    commands: [
      { cmd: "psql -U user -d dbname -h host", desc: "Connect to a Postgres database", type: "Connect" },
      { cmd: "pg_isready -h host -p 5432", desc: "Check if a Postgres server is accepting connections", type: "Connect" },
      { cmd: "\\l", desc: "List all databases (inside psql)", type: "Explore (psql)" },
      { cmd: "\\dt", desc: "List tables in the current schema (inside psql)", type: "Explore (psql)" },
      { cmd: "\\d tablename", desc: "Describe a table's columns/indexes (inside psql)", type: "Explore (psql)" },
      { cmd: "\\du", desc: "List roles/users (inside psql)", type: "Explore (psql)" },
      { cmd: "\\x", desc: "Toggle expanded output, one column per line (inside psql)", type: "Explore (psql)" },
      { cmd: "EXPLAIN ANALYZE SELECT ...;", desc: "Show the query plan with actual execution timing", type: "Explore (psql)" },
      { cmd: "\\copy table TO 'data.csv' WITH CSV HEADER;", desc: "Export a table to a CSV file (client-side, no server perms needed)", type: "Copy & Move" },
      { cmd: "\\copy table FROM 'data.csv' WITH CSV HEADER;", desc: "Import a CSV file into a table (client-side)", type: "Copy & Move" },
      { cmd: "CREATE TABLE new_table AS SELECT * FROM old_table;", desc: "Copy a table's structure and data into a new table", type: "Copy & Move" },
      { cmd: "CREATE INDEX idx_table_col ON table(col);", desc: "Add an index to speed up lookups on a column", type: "Schema" },
      { cmd: "ALTER TABLE table ADD COLUMN col INT;", desc: "Add a new column to a table", type: "Schema" },
      { cmd: "GRANT SELECT ON table TO username;", desc: "Grant read access on a table to a role", type: "Schema" },
      { cmd: "CREATE EXTENSION IF NOT EXISTS pgcrypto;", desc: "Install a Postgres extension into the current database", type: "Schema" },
      { cmd: "SELECT * FROM pg_stat_activity;", desc: "Show current connections and running queries", type: "Session & Locks" },
      { cmd: "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid = 1234;", desc: "Kill a specific backend/connection", type: "Session & Locks", danger: true },
      { cmd: "pg_dump -U user dbname > backup.sql", desc: "Dump a database to a SQL file", type: "Backup & Restore" },
      { cmd: "pg_dump -U user -Fc dbname > backup.dump", desc: "Dump in custom format, needed for pg_restore's selective restore", type: "Backup & Restore" },
      { cmd: "psql -U user dbname < backup.sql", desc: "Restore a database from a plain SQL dump", type: "Backup & Restore" },
      { cmd: "pg_basebackup -h host -D /backup -U repl -Fp -Xs -P", desc: "Take a full physical base backup for replication/PITR", type: "Backup & Restore" },
      { cmd: "VACUUM ANALYZE tablename;", desc: "Reclaim space and update planner statistics for a table", type: "Maintenance" },
      { cmd: "REINDEX TABLE tablename;", desc: "Rebuild a table's indexes, useful after heavy bloat", type: "Maintenance" },
      { cmd: "TRUNCATE tablename;", desc: "Remove all rows from a table instantly, faster than DELETE", type: "Maintenance", danger: true },
      { cmd: "DROP DATABASE dbname;", desc: "Permanently delete a database", type: "Maintenance", danger: true },
    ],
  },
  {
    id: "redis",
    label: "Redis",
    commands: [
      { cmd: "redis-cli -h host -p 6379", desc: "Connect to a Redis server", type: "Connect" },
      { cmd: "redis-cli -a password PING", desc: "Check server is alive (with auth)", type: "Connect" },
      { cmd: "redis-cli --tls -h host", desc: "Connect over TLS", type: "Connect" },
      { cmd: "KEYS *", desc: "List all keys (avoid in production, blocks the server)", type: "Keys" },
      { cmd: "SCAN 0 MATCH pattern:* COUNT 100", desc: "Iterate keys matching a pattern without blocking", type: "Keys" },
      { cmd: "GET key", desc: "Get the value of a string key", type: "Keys" },
      { cmd: "COPY source destination", desc: "Copy a key's value to a new key", type: "Copy & Move" },
      { cmd: "RENAME oldkey newkey", desc: "Rename a key", type: "Copy & Move" },
      { cmd: "MOVE key 1", desc: "Move a key to a different numbered database", type: "Copy & Move" },
      { cmd: "DUMP key", desc: "Serialize a key's value for backup/transfer", type: "Copy & Move" },
      { cmd: "RESTORE key 0 serializedvalue", desc: "Recreate a key from a DUMP payload", type: "Copy & Move" },
      { cmd: "TTL key", desc: "Show remaining time-to-live of a key in seconds", type: "Expiry" },
      { cmd: "EXPIRE key 3600", desc: "Set a key to expire in 3600 seconds", type: "Expiry" },
      { cmd: "PERSIST key", desc: "Remove the expiry from a key, making it permanent", type: "Expiry" },
      { cmd: "DEL key", desc: "Delete a key", type: "Destructive", danger: true },
      { cmd: "FLUSHDB", desc: "Delete all keys in the current database", type: "Destructive", danger: true },
      { cmd: "FLUSHALL", desc: "Delete all keys in all databases", type: "Destructive", danger: true },
      { cmd: "INFO", desc: "Show server stats: memory, clients, replication, etc", type: "Monitoring" },
      { cmd: "MONITOR", desc: "Stream every command processed by the server, live", type: "Monitoring" },
      { cmd: "redis-cli --bigkeys", desc: "Sample keyspace to find the largest keys", type: "Monitoring" },
      { cmd: "SLOWLOG GET 10", desc: "Show the 10 most recent slow queries", type: "Monitoring" },
      { cmd: "OBJECT ENCODING key", desc: "Show the internal storage encoding used for a key", type: "Monitoring" },
      { cmd: "CLUSTER INFO", desc: "Show cluster state when running in cluster mode", type: "Monitoring" },
      { cmd: "BGSAVE", desc: "Trigger an async RDB snapshot to disk", type: "Persistence" },
      { cmd: "BGREWRITEAOF", desc: "Trigger an async AOF file rewrite/compaction", type: "Persistence" },
      { cmd: "REPLICAOF host port", desc: "Make this instance a replica of another Redis server", type: "Persistence" },
      { cmd: "CONFIG GET maxmemory", desc: "Read a server config value", type: "Config" },
    ],
  },
  {
    id: "nats",
    label: "NATS",
    commands: [
      { cmd: "nats sub \"subject.>\"", desc: "Subscribe and print messages on a subject wildcard", type: "Pub/Sub" },
      { cmd: "nats pub subject \"payload\"", desc: "Publish a message to a subject", type: "Pub/Sub" },
      { cmd: "nats req subject \"payload\"", desc: "Send a request and wait for a reply", type: "Pub/Sub" },
      { cmd: "nats bench subject --pub 1 --sub 5 --msgs 100000", desc: "Load-test throughput with N publishers/subscribers", type: "Pub/Sub" },
      { cmd: "nats stream ls", desc: "List JetStream streams", type: "JetStream" },
      { cmd: "nats stream info STREAM", desc: "Show config/state of a JetStream stream", type: "JetStream" },
      { cmd: "nats stream add STREAM --subjects \"orders.>\"", desc: "Create a new JetStream stream capturing a subject pattern", type: "JetStream" },
      { cmd: "nats consumer ls STREAM", desc: "List consumers on a stream", type: "JetStream" },
      { cmd: "nats consumer add STREAM CONSUMER --pull", desc: "Create a new pull-based consumer on a stream", type: "JetStream" },
      { cmd: "nats stream purge STREAM", desc: "Delete all messages in a stream", type: "JetStream", danger: true },
      { cmd: "nats kv put BUCKET key value", desc: "Write a value to a JetStream key-value bucket", type: "Key/Object Store" },
      { cmd: "nats kv get BUCKET key", desc: "Read a value from a key-value bucket", type: "Key/Object Store" },
      { cmd: "nats object put BUCKET file.zip", desc: "Upload a file to a JetStream object store bucket", type: "Key/Object Store" },
      { cmd: "nats server check connection --server=host:4222", desc: "Check connectivity to a NATS server", type: "Server" },
      { cmd: "nats server ls", desc: "List known servers in the cluster", type: "Server" },
      { cmd: "nats server report jetstream", desc: "Cluster-wide JetStream usage report", type: "Server" },
      { cmd: "nats context save myctx --server host:4222 --creds file.creds", desc: "Save a named connection profile for quick reuse", type: "Server" },
      { cmd: "nats-server -c nats-server.conf", desc: "Start a NATS server with a config file", type: "Server" },
    ],
  },
  {
    id: "curl",
    label: "cURL",
    commands: [
      { cmd: "curl -i https://api.example.com/health", desc: "GET request, show response headers", type: "Basic" },
      { cmd: "curl -X POST -H \"Content-Type: application/json\" -d '{\"a\":1}' https://api.example.com", desc: "POST JSON body", type: "Basic" },
      { cmd: "curl -X PUT -d '{\"a\":2}' https://api.example.com/1", desc: "PUT request with a JSON body", type: "Basic" },
      { cmd: "curl -X PATCH -d '{\"a\":3}' https://api.example.com/1", desc: "PATCH request with a partial JSON body", type: "Basic" },
      { cmd: "curl -X DELETE https://api.example.com/1", desc: "DELETE request", type: "Basic", danger: true },
      { cmd: "curl -F \"file=@photo.jpg\" https://api.example.com/upload", desc: "Multipart file upload", type: "Basic" },
      { cmd: "curl -L https://short.url", desc: "Follow redirects", type: "Basic" },
      { cmd: "curl --data-urlencode \"q=hello world\" https://api.example.com/search", desc: "URL-encode a query parameter", type: "Basic" },
      { cmd: "curl -H \"Authorization: Bearer TOKEN\" https://api.example.com", desc: "Send a bearer token auth header", type: "Auth" },
      { cmd: "curl -u user:pass https://api.example.com", desc: "Basic auth", type: "Auth" },
      { cmd: "curl -c cookies.txt -b cookies.txt https://api.example.com", desc: "Persist and reuse cookies across requests", type: "Auth" },
      { cmd: "curl -o file.zip https://example.com/file.zip", desc: "Download a file to disk", type: "Transfer" },
      { cmd: "curl -O https://example.com/file.zip", desc: "Download, keeping the remote filename", type: "Transfer" },
      { cmd: "curl -C - -O https://example.com/big.iso", desc: "Resume a partially downloaded file", type: "Transfer" },
      { cmd: "curl --limit-rate 1M -O https://example.com/file.zip", desc: "Cap download speed, e.g. to avoid saturating a link", type: "Transfer" },
      { cmd: "curl -x http://proxy:8080 https://api.example.com", desc: "Route the request through an HTTP proxy", type: "Transfer" },
      { cmd: "curl -I https://api.example.com", desc: "HEAD request, headers only, no body", type: "Debug" },
      { cmd: "curl -v https://api.example.com", desc: "Verbose output including TLS handshake and headers", type: "Debug" },
      { cmd: "curl -k https://self-signed.local", desc: "Skip TLS certificate verification (dev only)", type: "Debug" },
      { cmd: "curl -w \"%{time_total}\\n\" -o /dev/null -s https://api.example.com", desc: "Print only the total request time", type: "Debug" },
      { cmd: "curl --retry 3 --retry-delay 2 https://api.example.com", desc: "Retry on transient failure with a delay between attempts", type: "Debug" },
    ],
  },
  {
    id: "network",
    label: "Network",
    commands: [
      { cmd: "ping host", desc: "Check reachability and round-trip latency", type: "Reachability" },
      { cmd: "traceroute host", desc: "Show the route packets take to a host (Linux/macOS)", type: "Reachability" },
      { cmd: "tracert host", desc: "Same as above on Windows", type: "Reachability" },
      { cmd: "mtr host", desc: "Live combination of ping + traceroute, per-hop loss and latency", type: "Reachability" },
      { cmd: "nc -zv host 443", desc: "Test if a TCP port is open", type: "Ports" },
      { cmd: "telnet host 23", desc: "Open a raw TCP connection to test a port interactively", type: "Ports" },
      { cmd: "netstat -tulpn", desc: "List listening ports and owning processes (Linux)", type: "Ports" },
      { cmd: "ss -tulpn", desc: "Faster modern replacement for netstat, same purpose", type: "Ports" },
      { cmd: "nslookup host", desc: "Resolve a hostname's DNS records", type: "DNS" },
      { cmd: "dig host +short", desc: "Concise DNS lookup", type: "DNS" },
      { cmd: "dig -x 1.2.3.4", desc: "Reverse DNS lookup for an IP", type: "DNS" },
      { cmd: "dig host MX", desc: "Look up a domain's mail exchange records", type: "DNS" },
      { cmd: "openssl s_client -connect host:443 -servername host", desc: "Inspect a server's TLS certificate chain and expiry", type: "TLS & Security" },
      { cmd: "openssl x509 -in cert.pem -noout -dates", desc: "Show a certificate file's validity dates", type: "TLS & Security" },
      { cmd: "whois domain.com", desc: "Look up domain registration info", type: "Info" },
      { cmd: "curl ifconfig.me", desc: "Show your public IP address", type: "Info" },
      { cmd: "arp -a", desc: "Show the local ARP table", type: "Info" },
      { cmd: "iperf3 -c host", desc: "Measure actual throughput to a host (needs iperf3 server on the other end)", type: "Info" },
    ],
  },
  {
    id: "dotnet",
    label: ".NET CLI",
    commands: [
      { cmd: "dotnet new webapi -n MyApi", desc: "Scaffold a new Web API project", type: "Scaffold & Run" },
      { cmd: "dotnet new sln", desc: "Create a new empty solution file", type: "Scaffold & Run" },
      { cmd: "dotnet sln add MyApi/MyApi.csproj", desc: "Add a project to a solution", type: "Scaffold & Run" },
      { cmd: "dotnet run", desc: "Build and run the project", type: "Scaffold & Run" },
      { cmd: "dotnet watch run", desc: "Run with hot-reload on file changes", type: "Scaffold & Run" },
      { cmd: "dotnet build", desc: "Build the project/solution", type: "Build & Test" },
      { cmd: "dotnet format", desc: "Apply code style/formatting fixes across the project", type: "Build & Test" },
      { cmd: "dotnet test", desc: "Run unit tests", type: "Build & Test" },
      { cmd: "dotnet test --filter FullyQualifiedName~MyTestClass", desc: "Run only tests matching a name filter", type: "Build & Test" },
      { cmd: "dotnet publish -c Release -o out", desc: "Publish a release build to a folder", type: "Publish" },
      { cmd: "dotnet publish -c Release -r win-x64 --self-contained true", desc: "Publish a self-contained build with the runtime bundled", type: "Publish" },
      { cmd: "dotnet ef migrations add InitName", desc: "Add a new EF Core migration", type: "EF Core" },
      { cmd: "dotnet ef database update", desc: "Apply pending EF Core migrations to the database", type: "EF Core" },
      { cmd: "dotnet ef migrations remove", desc: "Remove the last, not-yet-applied EF Core migration", type: "EF Core" },
      { cmd: "dotnet ef dbcontext script", desc: "Generate a SQL script for the full migration history", type: "EF Core" },
      { cmd: "dotnet add package PackageName", desc: "Add a NuGet package reference", type: "Packages" },
      { cmd: "dotnet list package --outdated", desc: "List installed packages that have newer versions available", type: "Packages" },
      { cmd: "dotnet restore", desc: "Restore NuGet dependencies", type: "Packages" },
      { cmd: "dotnet nuget locals all --clear", desc: "Clear all local NuGet caches", type: "Packages" },
      { cmd: "dotnet tool install --global dotnet-ef", desc: "Install a .NET global CLI tool", type: "Packages" },
      { cmd: "dotnet user-secrets set \"Key\" \"value\"", desc: "Store a dev-only secret outside of source control", type: "Packages" },
      { cmd: "dotnet --list-sdks", desc: "List installed .NET SDK versions", type: "Packages" },
    ],
  },
  {
    id: "npm",
    label: "NPM / Node",
    commands: [
      { cmd: "npm init -y", desc: "Create a package.json with default values", type: "Install" },
      { cmd: "npm install", desc: "Install dependencies from package.json/lockfile", type: "Install" },
      { cmd: "npm ci", desc: "Clean install exactly matching the lockfile (CI-safe)", type: "Install" },
      { cmd: "npm install pkg --save-dev", desc: "Install a package as a dev-only dependency", type: "Install" },
      { cmd: "npx package-name", desc: "Run a package's CLI without installing it globally", type: "Install" },
      { cmd: "npm run dev", desc: "Run the \"dev\" script", type: "Run & Dev" },
      { cmd: "npm run build", desc: "Run the \"build\" script", type: "Run & Dev" },
      { cmd: "npm link", desc: "Symlink a local package into another project for live development", type: "Run & Dev" },
      { cmd: "node --version", desc: "Show the installed Node.js version", type: "Run & Dev" },
      { cmd: "nvm use 20", desc: "Switch active Node version (with nvm installed)", type: "Run & Dev" },
      { cmd: "npm outdated", desc: "List installed packages with newer versions available", type: "Maintenance" },
      { cmd: "npm update package", desc: "Update a package within its semver range", type: "Maintenance" },
      { cmd: "npm uninstall package", desc: "Remove a package", type: "Maintenance" },
      { cmd: "npm dedupe", desc: "Simplify the dependency tree by flattening duplicate packages", type: "Maintenance" },
      { cmd: "npm audit fix", desc: "Attempt to auto-fix known vulnerabilities", type: "Maintenance" },
      { cmd: "npm list --depth=0", desc: "Show top-level installed dependencies", type: "Maintenance" },
      { cmd: "npm cache clean --force", desc: "Clear the local npm cache", type: "Maintenance" },
      { cmd: "npm version patch", desc: "Bump the package's patch version and create a git tag", type: "Publishing" },
      { cmd: "npm pack", desc: "Build the package into a .tgz tarball without publishing", type: "Publishing" },
      { cmd: "npm publish", desc: "Publish the package to the npm registry", type: "Publishing", danger: true },
      { cmd: "npm config set registry https://registry.example.com", desc: "Point npm at a different package registry", type: "Publishing" },
    ],
  },
  {
    id: "azure",
    label: "Azure / Cloud",
    commands: [
      { cmd: "az login", desc: "Sign in to Azure interactively", type: "Account & Setup" },
      { cmd: "az account list --output table", desc: "List subscriptions available to the signed-in account", type: "Account & Setup" },
      { cmd: "az account set --subscription \"Name or Id\"", desc: "Switch the active subscription for subsequent commands", type: "Account & Setup" },
      { cmd: "az group create --name rg-name --location eastus", desc: "Create a resource group", type: "Resource Groups" },
      { cmd: "az group list --output table", desc: "List all resource groups in the subscription", type: "Resource Groups" },
      { cmd: "az group delete --name rg-name --yes --no-wait", desc: "Delete a resource group and everything inside it", type: "Resource Groups", danger: true },
      { cmd: "az resource list --resource-group rg-name --output table", desc: "List all resources in a resource group", type: "Resource Groups" },
      { cmd: "az vm list --output table", desc: "List virtual machines", type: "Virtual Machines" },
      { cmd: "az vm start --resource-group rg-name --name vm-name", desc: "Start a stopped VM", type: "Virtual Machines" },
      { cmd: "az vm stop --resource-group rg-name --name vm-name", desc: "Stop (deallocate) a running VM", type: "Virtual Machines" },
      { cmd: "az vm restart --resource-group rg-name --name vm-name", desc: "Restart a VM", type: "Virtual Machines" },
      { cmd: "az vm delete --resource-group rg-name --name vm-name --yes", desc: "Permanently delete a VM", type: "Virtual Machines", danger: true },
      { cmd: "az ssh vm --resource-group rg-name --name vm-name", desc: "SSH into a VM using Azure AD/AAD login, no key management", type: "Virtual Machines" },
      { cmd: "az webapp list --output table", desc: "List App Service web apps", type: "App Service" },
      { cmd: "az webapp create --name app-name --resource-group rg-name --plan plan-name", desc: "Create a new App Service web app", type: "App Service" },
      { cmd: "az webapp deploy --name app-name --resource-group rg-name --src-path ./publish.zip", desc: "Deploy a zip package to an App Service app", type: "App Service" },
      { cmd: "az webapp restart --name app-name --resource-group rg-name", desc: "Restart an App Service app", type: "App Service" },
      { cmd: "az webapp log tail --name app-name --resource-group rg-name", desc: "Stream live logs from an App Service app", type: "App Service" },
      { cmd: "az webapp config appsettings set --name app-name --resource-group rg-name --settings KEY=value", desc: "Set an app setting / environment variable", type: "App Service" },
      { cmd: "az functionapp list --output table", desc: "List Function Apps", type: "Functions" },
      { cmd: "az functionapp deployment source config-zip --name func-name --resource-group rg-name --src ./publish.zip", desc: "Deploy a zip package to a Function App", type: "Functions" },
      { cmd: "func start", desc: "Run Azure Functions locally (Azure Functions Core Tools)", type: "Functions" },
      { cmd: "az storage account list --output table", desc: "List storage accounts", type: "Storage" },
      { cmd: "az storage account keys list --account-name acct --resource-group rg-name", desc: "Show access keys for a storage account", type: "Storage" },
      { cmd: "az storage blob upload --account-name acct --container-name c --name file.txt --file ./file.txt", desc: "Upload a file to blob storage", type: "Storage" },
      { cmd: "az storage blob download --account-name acct --container-name c --name file.txt --file ./file.txt", desc: "Download a blob to a local file", type: "Storage" },
      { cmd: "az storage blob list --account-name acct --container-name c --output table", desc: "List blobs in a container", type: "Storage" },
      { cmd: "azcopy copy \"src\" \"https://acct.blob.core.windows.net/c/dest\" --recursive", desc: "High-throughput copy of files/folders to/from blob storage", type: "Storage" },
      { cmd: "az sql server create --name sql-server --resource-group rg-name --admin-user admin --admin-password pass", desc: "Create an Azure SQL logical server", type: "Databases" },
      { cmd: "az sql db create --resource-group rg-name --server sql-server --name db-name --service-objective S0", desc: "Create an Azure SQL database", type: "Databases" },
      { cmd: "az postgres flexible-server create --name pg-server --resource-group rg-name", desc: "Create an Azure Database for PostgreSQL flexible server", type: "Databases" },
      { cmd: "az cosmosdb list --output table", desc: "List Cosmos DB accounts", type: "Databases" },
      { cmd: "az aks get-credentials --name aks-name --resource-group rg-name", desc: "Fetch AKS cluster credentials into local kubeconfig", type: "AKS / Containers" },
      { cmd: "az aks list --output table", desc: "List AKS clusters", type: "AKS / Containers" },
      { cmd: "az aks scale --name aks-name --resource-group rg-name --node-count 3", desc: "Scale an AKS cluster's node pool", type: "AKS / Containers" },
      { cmd: "az acr login --name registryName", desc: "Authenticate Docker to an Azure Container Registry", type: "AKS / Containers" },
      { cmd: "az acr build --registry registryName --image app:v1 .", desc: "Build and push a Docker image via ACR Tasks (no local Docker needed)", type: "AKS / Containers" },
      { cmd: "az keyvault secret list --vault-name vault-name --output table", desc: "List secrets in a Key Vault", type: "Key Vault & Identity" },
      { cmd: "az keyvault secret show --vault-name vault-name --name secret-name --query value -o tsv", desc: "Read a secret's value", type: "Key Vault & Identity" },
      { cmd: "az keyvault secret set --vault-name vault-name --name secret-name --value \"val\"", desc: "Create or update a secret", type: "Key Vault & Identity" },
      { cmd: "az ad sp create-for-rbac --name sp-name --role Contributor --scopes /subscriptions/{id}", desc: "Create a service principal for CI/CD or app auth", type: "Key Vault & Identity" },
      { cmd: "az monitor activity-log list --resource-group rg-name --output table", desc: "Show recent control-plane activity (who did what) for a resource group", type: "Monitoring & Logs" },
      { cmd: "az monitor metrics list --resource resourceId --metric \"Percentage CPU\"", desc: "Query a resource's metrics, e.g. CPU usage", type: "Monitoring & Logs" },
      { cmd: "az monitor log-analytics query --workspace workspaceId --analytics-query \"AppRequests | take 20\"", desc: "Run a Kusto (KQL) query against Log Analytics / App Insights", type: "Monitoring & Logs" },
      { cmd: "az deployment group create --resource-group rg-name --template-file main.bicep", desc: "Deploy a Bicep/ARM template to a resource group", type: "Deployment (IaC)" },
      { cmd: "az deployment group what-if --resource-group rg-name --template-file main.bicep", desc: "Preview what a template deployment would change, without applying it", type: "Deployment (IaC)" },
      { cmd: "az bicep build --file main.bicep", desc: "Compile a Bicep file to ARM JSON", type: "Deployment (IaC)" },
    ],
  },
];
