import type { Question } from "./types";

/** Messaging, queues and the distributed-systems patterns that go with them. */
export const MESSAGING_QUESTIONS: Question[] = [
  {
    id: "msg-why-queue",
    topic: "messaging",
    subtopic: "Fundamentals",
    level: "basic",
    mustKnow: true,
    question: "Why put a queue between two services instead of calling directly?",
    answer: `A queue converts a **temporal coupling** into a **durable handoff**.

- **Availability** — the producer succeeds even when the consumer is down; work waits instead of failing.
- **Load levelling** — a spike becomes a longer queue, not a crashed consumer. The consumer works at its own rate.
- **Scaling** — add consumers to drain faster (competing consumers).
- **Decoupling** — the producer does not know who handles the message, or how many do.

The costs are real and interviewers expect you to name them: **eventual consistency** (the caller cannot see the result immediately), **at-least-once delivery** (duplicates, so handlers must be idempotent), **ordering** is no longer free, and **debugging** spans two processes and a broker.`,
    diagram: `Synchronous                          Asynchronous
  API --HTTP--> Service B              API --> [ queue ] --> Worker
   |             (down = 500)                    |            (down = messages wait)
   +-- caller waits for B                        +-- caller returns immediately`,
    followUps: [
      {
        question: "When is a direct synchronous call the better choice?",
        answer:
          "When the caller needs the result to continue — a price quote, an authorisation decision, a read. Queueing a request whose answer you must wait for adds latency and complexity for nothing.",
      },
    ],
    tags: ["queue", "decoupling", "async", "load levelling"],
  },
  {
    id: "msg-delivery-guarantees",
    topic: "messaging",
    subtopic: "Fundamentals",
    level: "intermediate",
    mustKnow: true,
    question: "At-most-once, at-least-once, exactly-once — what is real?",
    answer: `- **At-most-once** — deliver and forget. Messages can be lost. Acceptable for metrics or telemetry.
- **At-least-once** — the broker redelivers until acknowledged. Messages can be **duplicated**. This is what almost every real system uses.
- **Exactly-once** — not achievable end-to-end across a network in general. What systems provide is either exactly-once *processing within the broker's own boundary* (Kafka transactions between topics) or at-least-once delivery plus an **idempotent consumer**, which is observationally the same thing.

So the practical answer: **at-least-once delivery + idempotent handlers = effectively exactly once**. Say that, and interviewers stop probing.`,
    language: "csharp",
    code: `// Idempotent consumer: the message id is recorded in the same transaction as the work
public async Task HandleAsync(OrderPlaced message, CancellationToken ct)
{
    await using var tx = await _db.Database.BeginTransactionAsync(ct);

    var alreadyDone = await _db.ProcessedMessages.AnyAsync(m => m.Id == message.MessageId, ct);
    if (alreadyDone) return;                       // duplicate: safely ignored

    _db.Orders.Add(new Order(message.OrderId, message.Total));
    _db.ProcessedMessages.Add(new ProcessedMessage(message.MessageId, DateTime.UtcNow));

    await _db.SaveChangesAsync(ct);                // work + dedup record commit together
    await tx.CommitAsync(ct);
}`,
    followUps: [
      {
        question: "Why can't you just acknowledge before processing?",
        answer:
          "Then a crash mid-processing loses the message — you have converted duplicates into data loss, which is usually worse.",
      },
      {
        question: "What makes a natural idempotency key?",
        answer:
          "Something derived from the business event: order id + event type, or a producer-generated message id. A random id generated by the consumer is useless because a redelivery generates a new one.",
      },
    ],
    tags: ["delivery", "at-least-once", "idempotency", "exactly-once", "duplicates"],
  },
  {
    id: "msg-kafka-vs-rabbit",
    topic: "messaging",
    subtopic: "Brokers",
    level: "intermediate",
    mustKnow: true,
    question: "Kafka vs RabbitMQ — how do you choose?",
    answer: `They are different tools, not competitors.

**RabbitMQ** — a *message broker*. Messages are routed through exchanges to queues and **removed when acknowledged**. Rich routing (direct, topic, fanout, headers), per-message TTL, priorities, dead-letter exchanges. Best for task distribution and commands.

**Kafka** — a *distributed log*. Messages are appended to partitions and **retained** for a configured period regardless of consumption. Consumers track their own offset, so they can replay history and new consumer groups can read from the beginning. Best for event streaming, audit logs, and feeding multiple independent consumers.

Deciding questions: do you need **replay**? (Kafka) Do you need **complex routing per message**? (Rabbit) Is throughput in the millions/sec? (Kafka) Do you need per-message ack and retry semantics? (Rabbit)`,
    diagram: `RabbitMQ — messages leave the queue
  producer -> [exchange] -routing key-> [queue] -> consumer (ack -> deleted)

Kafka — the log stays; consumers hold offsets
  producer -> [ partition 0: m1 m2 m3 m4 ... ]
                          ^        ^
                   group A offset  group B offset  (independent, replayable)`,
    followUps: [
      {
        question: "How does Kafka guarantee ordering?",
        answer:
          "Per partition only. Messages with the same key hash to the same partition, so choose the key as the entity whose order matters (customer id, account id). Global ordering means one partition, which means no parallelism.",
      },
      {
        question: "What is a consumer group?",
        answer:
          "A set of consumers sharing the partitions of a topic — each partition is read by exactly one member, so the group scales up to the partition count. Different groups read the same data independently.",
      },
    ],
    tags: ["kafka", "rabbitmq", "broker", "partitions", "consumer group"],
  },
  {
    id: "msg-dlq",
    topic: "messaging",
    subtopic: "Reliability",
    level: "intermediate",
    mustKnow: true,
    question: "What is a dead-letter queue and how should it be used?",
    answer: `A DLQ holds messages that could not be processed: delivery count exceeded, expired, malformed, or explicitly rejected.

Its purpose is to **stop one bad message blocking the queue** (the poison message problem) while keeping it for inspection instead of losing it.

Operating it properly:

- **Alert on depth > 0.** A DLQ nobody watches is a silent data-loss mechanism.
- **Keep the failure reason** — Service Bus records \`DeadLetterReason\`; log correlation ids so the original context is findable.
- **Have a replay path** — fix the bug, then resubmit. Ad-hoc scripts written during an incident are how messages get lost twice.
- **Distinguish poison from outage.** A dependency being down should be retried with backoff, not dead-lettered after three quick attempts.`,
    language: "csharp",
    code: `var options = new ServiceBusProcessorOptions
{
    MaxConcurrentCalls = 8,
    AutoCompleteMessages = false        // acknowledge explicitly, after success
};

processor.ProcessMessageAsync += async args =>
{
    try
    {
        await _handler.HandleAsync(args.Message.Body.ToObjectFromJson<OrderPlaced>());
        await args.CompleteMessageAsync(args.Message);            // remove from the queue
    }
    catch (ValidationException ex)
    {
        // Never going to succeed: fail fast rather than burning retries
        await args.DeadLetterMessageAsync(args.Message, "ValidationFailed", ex.Message);
    }
    catch (Exception)
    {
        await args.AbandonMessageAsync(args.Message);             // retry, count increments
    }
};`,
    followUps: [
      {
        question: "What is a poison message?",
        answer:
          "One that always fails — bad schema, a reference to something deleted. Without a delivery limit it is retried forever, blocking or looping. The delivery count plus DLQ is the standard defence.",
      },
    ],
    tags: ["dlq", "poison message", "retry", "service bus", "reliability"],
  },
  {
    id: "msg-outbox",
    topic: "messaging",
    subtopic: "Patterns",
    level: "advanced",
    mustKnow: true,
    question: "How do you avoid losing a message when the database commit succeeds but publishing fails?",
    answer: `This is the **dual-write problem**: a database and a broker cannot be committed atomically without distributed transactions, which nobody wants.

The **Transactional Outbox** solves it:

1. In the same database transaction as the business change, insert the message into an \`Outbox\` table.
2. Commit once — either both happened or neither did.
3. A separate publisher reads unsent rows, publishes to the broker, and marks them sent.

Because the publisher can crash between publish and mark, delivery is at-least-once — so consumers must still be idempotent. The **Inbox** pattern is the mirror image on the consumer side, recording processed message ids.`,
    diagram: `        one transaction
  +------------------------------+
  |  INSERT Order                |
  |  INSERT Outbox(event)        |
  +---------------+--------------+
                  | commit
                  v
          [ Outbox table ] <---- publisher polls unsent
                                  |
                                  v  publish, then mark Sent
                            [ broker ] --> consumers (idempotent)`,
    language: "sql",
    code: `CREATE TABLE Outbox (
    Id          uniqueidentifier PRIMARY KEY,
    Type        nvarchar(200)    NOT NULL,
    Payload     nvarchar(max)    NOT NULL,
    OccurredAt  datetime2        NOT NULL,
    SentAt      datetime2        NULL
);
CREATE INDEX IX_Outbox_Unsent ON Outbox (OccurredAt) WHERE SentAt IS NULL;

-- Publisher claims rows without two instances taking the same one
UPDATE TOP (100) Outbox WITH (READPAST, UPDLOCK)
SET    SentAt = SYSUTCDATETIME()
OUTPUT inserted.Id, inserted.Type, inserted.Payload
WHERE  SentAt IS NULL;`,
    followUps: [
      {
        question: "What is Change Data Capture's role here?",
        answer:
          "An alternative to polling: CDC or logical decoding tails the transaction log and publishes committed changes (the Debezium approach). Lower latency and no polling load, at the cost of more infrastructure.",
      },
      {
        question: "Why not just publish first, then save?",
        answer:
          "Then a failure after publishing leaves consumers acting on something that never happened in your database — a phantom order. Losing a message is recoverable; inventing one is not.",
      },
    ],
    tags: ["outbox", "dual write", "saga", "consistency", "cdc"],
  },
  {
    id: "msg-saga",
    topic: "messaging",
    subtopic: "Patterns",
    level: "advanced",
    question: "How do you handle a transaction spanning several services?",
    answer: `You cannot hold a database transaction across services, so use a **Saga**: a sequence of local transactions, each publishing an event, with a **compensating action** for every step that may need undoing.

Two styles:

- **Choreography** — each service reacts to events. No coordinator, loose coupling, but the overall flow exists only in people's heads and is hard to debug.
- **Orchestration** — a coordinator tells each service what to do next and handles failures. The flow is explicit and observable; the orchestrator is another component to run.

Compensation is not rollback: you cannot un-send an email, so you send a correction. Design compensations as real business operations (refund, cancel, restock).`,
    diagram: `Orchestrated saga — order placement

 [Orchestrator]
   | 1 ReserveStock  ---> [Inventory]  ok
   | 2 TakePayment   ---> [Payments]   FAILS
   | 3 compensate    ---> [Inventory] ReleaseStock
   | 4 mark order failed, notify customer

Each step: local transaction + event. No global lock anywhere.`,
    followUps: [
      {
        question: "How do you keep a saga from getting stuck?",
        answer:
          "Every step needs a timeout and a defined action when it fires. A saga waiting forever for an event that will never arrive is the most common production failure of this pattern.",
      },
      {
        question: "Choreography or orchestration for a new system?",
        answer:
          "Orchestration for anything with more than about three steps or with money involved — you need to see and query the state. Choreography for simple reactive fan-out.",
      },
    ],
    tags: ["saga", "compensation", "orchestration", "choreography", "distributed transaction"],
  },
  {
    id: "msg-ordering",
    topic: "messaging",
    subtopic: "Fundamentals",
    level: "advanced",
    question: "How do you preserve message ordering when you also want parallelism?",
    answer: `Ordering and parallelism conflict directly: strict global order means one consumer, one at a time.

The resolution is that you rarely need *global* order — you need order **per entity**. Partition by that entity:

- **Kafka** — partition key = entity id; ordering is guaranteed within a partition.
- **Service Bus** — sessions; all messages with a session id go to one consumer in order.
- **RabbitMQ** — consistent-hash exchange, or one queue per entity group.

Then parallelism equals the number of partitions/sessions, and each entity's events stay in order.

Also design so order matters less: include a version or timestamp and let consumers ignore stale updates. That makes out-of-order delivery survivable rather than fatal.`,
    language: "csharp",
    code: `// Kafka: same key -> same partition -> ordered for that account
await producer.ProduceAsync("transactions",
    new Message<string, string> { Key = accountId, Value = json });

// Service Bus session: ordered per customer, parallel across customers
await sender.SendMessageAsync(new ServiceBusMessage(json) { SessionId = customerId });

// Version guard: a late message cannot overwrite newer state
if (incoming.Version <= current.Version) return;   // stale, ignore`,
    followUps: [
      {
        question: "What breaks ordering even within a partition?",
        answer:
          "Retries with concurrent in-flight requests: if message 2 succeeds while message 1 is being retried, they land out of order. Kafka's idempotent producer with `max.in.flight` constrained prevents this.",
      },
    ],
    tags: ["ordering", "partition key", "sessions", "parallelism"],
  },
  {
    id: "msg-backpressure",
    topic: "messaging",
    subtopic: "Reliability",
    level: "advanced",
    question: "The queue is growing faster than consumers drain it. What do you do?",
    answer: `Diagnose before scaling — adding consumers to a downstream bottleneck just moves the queue.

1. **Is the consumer slow or blocked?** Check per-message processing time and where it goes. Usually a downstream dependency (database, API), not the broker.
2. **Scale consumers** if the work is parallelisable and the downstream can take it. Autoscale on queue depth (KEDA does this well).
3. **Increase partitions/sessions** if parallelism is capped by them — in Kafka, consumers beyond the partition count sit idle.
4. **Batch** — process 100 messages per database round trip instead of one.
5. **Shed load** — drop or downgrade low-value messages, apply TTL so stale work expires rather than being processed pointlessly.
6. **Apply backpressure to producers** if the system genuinely cannot keep up; unbounded queues just move the failure later and make it worse.

Alert on **queue depth trend and message age**, not just depth: age tells you whether you are falling behind.`,
    followUps: [
      {
        question: "Why is message age a better alert than queue length?",
        answer:
          "A deep queue draining quickly is fine. A shallow queue whose oldest message is 40 minutes old means processing is stuck. Age measures the user-visible symptom.",
      },
    ],
    tags: ["backpressure", "scaling", "keda", "batching", "monitoring"],
  },
  {
    id: "msg-pubsub-vs-queue",
    topic: "messaging",
    subtopic: "Fundamentals",
    level: "basic",
    question: "Queue vs publish/subscribe — what is the difference?",
    answer: `**Queue (point-to-point)** — one message, one consumer. Several consumers compete; each message is handled once. Use for *commands*: "charge this card".

**Publish/subscribe** — one message, many independent subscribers, each getting its own copy. Use for *events*: "an order was placed", where billing, shipping and analytics all care and none of them is *the* handler.

The design consequence: with a queue the producer knows work must happen; with pub/sub the producer states a fact and does not care who reacts. Getting this backwards — publishing an event and assuming exactly one consumer acts — is a common source of duplicated side effects.`,
    diagram: `Queue (competing consumers)        Topic (pub/sub)
  [ q ] --> consumer A                [ topic ] --> sub: billing
        --> consumer B                          --> sub: shipping
   each message to ONE of them                  --> sub: analytics
                                            each message to ALL`,
    followUps: [
      {
        question: "Command or event — how do you name them?",
        answer:
          "Commands are imperative and directed: `ChargePayment`. Events are past tense and factual: `PaymentCharged`. If you find yourself naming an event imperatively, it is really a command.",
      },
    ],
    tags: ["queue", "pubsub", "topic", "commands", "events"],
  },
  {
    id: "msg-schema-evolution",
    topic: "messaging",
    subtopic: "Design",
    level: "advanced",
    question: "How do you change a message schema without breaking consumers?",
    answer: `Producers and consumers deploy independently, so **both versions coexist** during every rollout.

Safe changes: **adding an optional field**, adding a new message type, widening a value set consumers already ignore.

Breaking changes: removing or renaming a field, changing a type, changing a field's meaning, making an optional field required.

Techniques:

- **Tolerant reader** — ignore unknown fields, tolerate missing ones with defaults.
- **Versioned message types** — \`OrderPlacedV2\` published alongside V1 until consumers migrate.
- **Schema registry** (Kafka/Avro) enforcing compatibility rules at publish time, so an incompatible change is rejected before it reaches production.
- **Never reuse a field name** for a different meaning — that is the one change no reader can detect.`,
    language: "csharp",
    code: `// V1 consumers keep working: the new field is optional with a default
public record OrderPlaced(
    Guid OrderId,
    decimal Total,
    string Currency = "INR",          // added in V2, defaulted for old messages
    string? PromotionCode = null);

// Deserialisation must not fail on fields it does not know
var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true
    // System.Text.Json ignores unknown properties by default — keep it that way
};`,
    followUps: [
      {
        question: "How do you retire an old message version?",
        answer:
          "Publish both, measure consumption of V1 with telemetry, and only stop publishing when it reaches zero for longer than your longest consumer outage. Announcing a date without measuring is how it breaks.",
      },
    ],
    tags: ["schema", "versioning", "compatibility", "tolerant reader", "avro"],
  },
];
