import { lazy, type ComponentType } from "react";
import {
  Braces,
  GitCompareArrows,
  FileCode2,
  KeyRound,
  Fingerprint,
  Clock,
  Binary,
  Link2,
  Regex,
  Network,
  Send,
  Server,
  Code2,
  FileText,
  Database,
  FileJson2,
  Boxes,
  Stethoscope,
  HeartPulse,
  TestTubes,
  EyeOff,
  BookText,
  Webhook,
  PlugZap,
  GraduationCap,
  Container,
  Cpu,
  Radio,
  ListChecks,
  ScrollText,
  HardDrive,
  Rabbit,
  CloudCog,
  ArrowLeftRight,
  ScanSearch,
  Antenna,
  Bug,
  FileSearch,
  ShieldAlert,
  FlaskConical,
  Layers,
  PackageSearch,
  Bookmark,
  FolderKanban,
  TerminalSquare,
  Database as DatabaseIcon,
  Bug as BugIcon,
  Route as RouteIcon,
  FileCog,
  CalendarClock,
  Map as MapIcon,
  NotebookPen,
  Cable,
} from "lucide-react";
import type { Tool } from "./types";

// Tool screens are lazy-loaded so heavy libraries (sql-formatter, xml/yaml parsers,
// HTTP client) are only pulled in when a tool is actually opened. Startup stays small.
const L = <T extends Record<string, ComponentType>>(
  loader: () => Promise<T>,
  key: keyof T,
) => lazy(() => loader().then((m) => ({ default: m[key] })));

export const TOOLS: Tool[] = [
  {
    id: "learn-hub",
    name: "Interview Prep",
    description: "Q&A bank for C#, .NET, Azure, DB, messaging, DSA and system design — with revision mode",
    category: "learn",
    icon: GraduationCap,
    keywords: [
      "interview", "learn", "revise", "study", "questions", "answers", "prep",
      "csharp", "c#", "oop", "solid", "dotnet", "azure", "sql", "database",
      "kafka", "rabbitmq", "queue", "dsa", "algorithms", "system design", "flashcard",
    ],
    route: "/tools/learn-hub",
    shortcut: "Ctrl+Shift+L",
    component: L(() => import("./impl/LearnHub"), "LearnHub"),
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, explore as a tree and query JSON with JSONPath",
    category: "data",
    icon: Braces,
    keywords: [
      "json",
      "format",
      "beautify",
      "pretty",
      "minify",
      "validate",
      "sort",
      "tree",
      "explorer",
      "jsonpath",
      "query",
      "filter",
      "escape",
      "unescape",
      "comments",
    ],
    route: "/tools/json-formatter",
    shortcut: "Ctrl+Shift+J",
    component: L(() => import("./impl/JsonFormatter"), "JsonFormatter"),
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Structural diff of two JSON documents",
    category: "data",
    icon: GitCompareArrows,
    keywords: ["json", "diff", "compare", "difference"],
    route: "/tools/json-diff",
    component: L(() => import("./impl/JsonDiff"), "JsonDiff"),
  },
  {
    id: "json-to-csharp",
    name: "JSON → C#",
    description: "Generate C# classes/records from JSON",
    category: "data",
    icon: FileCode2,
    keywords: ["json", "csharp", "c#", "class", "record", "model", "poco", "dto"],
    route: "/tools/json-to-csharp",
    component: L(() => import("./impl/JsonToCsharp"), "JsonToCsharp"),
  },
  {
    id: "xml-tools",
    name: "XML Tools",
    description: "Format, validate, convert XML ↔ JSON",
    category: "data",
    icon: Code2,
    keywords: ["xml", "format", "minify", "validate", "xml to json", "json to xml"],
    route: "/tools/xml-tools",
    component: L(() => import("./impl/XmlTool"), "XmlTool"),
  },
  {
    id: "yaml-tools",
    name: "YAML Tools",
    description: "Format, validate, convert YAML ↔ JSON",
    category: "data",
    icon: FileText,
    keywords: ["yaml", "yml", "format", "validate", "yaml to json", "json to yaml"],
    route: "/tools/yaml-tools",
    component: L(() => import("./impl/YamlTool"), "YamlTool"),
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify SQL across dialects",
    category: "data",
    icon: Database,
    keywords: ["sql", "format", "beautify", "query", "tsql", "postgres", "mysql"],
    route: "/tools/sql-formatter",
    component: L(() => import("./impl/SqlFormatter"), "SqlFormatter"),
  },
  {
    id: "api-tester",
    name: "API Tester",
    description: "Send HTTP requests, inspect responses, generate code",
    category: "api",
    icon: Send,
    keywords: ["api", "http", "rest", "request", "get", "post", "curl", "client", "fetch"],
    route: "/tools/api-tester",
    shortcut: "Ctrl+Shift+A",
    component: L(() => import("./impl/ApiTester"), "ApiTester"),
  },
  {
    id: "websocket-tester",
    name: "WebSocket Tester",
    description: "Connect over ws/wss with custom handshake headers and stream frames",
    category: "api",
    icon: PlugZap,
    keywords: ["websocket", "ws", "wss", "socket", "realtime", "stream", "frames", "signalr", "graphql-ws", "stomp"],
    route: "/tools/websocket-tester",
    requiresNative: true,
    component: L(() => import("./impl/WebSocketTester"), "WebSocketTester"),
  },
  {
    id: "environments",
    name: "Environment Manager",
    description: "DEV/QA/UAT/PROD variables for API requests",
    category: "api",
    icon: Server,
    keywords: ["environment", "env", "variables", "dev", "qa", "uat", "prod", "base url"],
    route: "/tools/environments",
    component: L(() => import("./impl/Environments"), "Environments"),
  },
  {
    id: "openapi",
    name: "OpenAPI / Swagger",
    description: "Import specs to collections; compare contracts for breaking changes",
    category: "api",
    icon: FileJson2,
    keywords: ["openapi", "swagger", "spec", "import", "contract", "diff", "breaking", "endpoints"],
    route: "/tools/openapi",
    component: L(() => import("./impl/OpenApiTool"), "OpenApiTool"),
  },
  {
    id: "test-data-generator",
    name: "Test Data Generator",
    description: "Generate synthetic records (JSON/CSV/SQL/XML)",
    category: "testing",
    icon: Boxes,
    keywords: ["test", "data", "fake", "mock", "generate", "seed", "csv", "sql", "sample"],
    route: "/tools/test-data-generator",
    component: L(() => import("./impl/TestDataGenerator"), "TestDataGenerator"),
  },
  {
    id: "hl7-toolkit",
    name: "HL7 Toolkit",
    description: "Parse, explore and convert HL7 v2 messages",
    category: "healthcare",
    icon: Stethoscope,
    keywords: ["hl7", "health level 7", "segment", "pid", "msh", "adt", "oru", "parse", "hl7 to json"],
    route: "/tools/hl7-toolkit",
    component: L(() => import("./impl/Hl7Toolkit"), "Hl7Toolkit"),
  },
  {
    id: "fhir-toolkit",
    name: "FHIR Toolkit",
    description: "Validate and explore FHIR R4 resources",
    category: "healthcare",
    icon: HeartPulse,
    keywords: ["fhir", "r4", "patient", "observation", "resource", "healthcare", "validate"],
    route: "/tools/fhir-toolkit",
    component: L(() => import("./impl/FhirToolkit"), "FhirToolkit"),
  },
  {
    id: "astm-toolkit",
    name: "ASTM Toolkit",
    description: "Parse ASTM E1394 lab messages, check E1381 framing",
    category: "healthcare",
    icon: TestTubes,
    keywords: ["astm", "e1394", "e1381", "lis", "analyzer", "lab", "checksum", "frame", "stx", "etx", "result"],
    route: "/tools/astm-toolkit",
    component: L(() => import("./impl/AstmToolkit"), "AstmToolkit"),
  },
  {
    id: "healthcare-deidentifier",
    name: "Healthcare De-identifier",
    description: "Detect and remove sensitive data locally",
    category: "healthcare",
    icon: EyeOff,
    keywords: ["deidentify", "anonymize", "phi", "pii", "mask", "redact", "mrn", "sensitive"],
    route: "/tools/healthcare-deidentifier",
    component: L(() => import("./impl/HealthcareDeidentifier"), "HealthcareDeidentifier"),
  },
  {
    id: "medical-text-utility",
    name: "Medical Text Utility",
    description: "Expand medical abbreviations (terminology only)",
    category: "healthcare",
    icon: BookText,
    keywords: ["medical", "abbreviation", "terminology", "expand", "hl7", "notes"],
    route: "/tools/medical-text-utility",
    component: L(() => import("./impl/MedicalTextUtility"), "MedicalTextUtility"),
  },
  {
    id: "soap-tester",
    name: "SOAP / XML Tester",
    description: "Build and send SOAP requests, inspect responses",
    category: "healthcare",
    icon: Webhook,
    keywords: ["soap", "xml", "envelope", "wsdl", "webservice", "request"],
    route: "/tools/soap-tester",
    component: L(() => import("./impl/SoapTester"), "SoapTester"),
  },
  {
    id: "device-link",
    name: "Device Link",
    description: "Talk to an analyser or interface engine — MLLP over TCP, ASTM E1381 over serial, with auto-ACK and a byte-level transcript",
    category: "healthcare",
    icon: Cable,
    keywords: [
      "device", "analyser", "analyzer", "instrument", "interface", "engine", "mllp", "hl7",
      "astm", "e1381", "e1394", "serial", "rs232", "rs-232", "com port", "tcp", "socket",
      "listener", "ack", "nak", "enq", "eot", "frame", "checksum", "lis", "lims", "his",
      "middleware", "mirth", "rhapsody", "sysmex", "mindray", "roche", "erba", "cobas",
    ],
    route: "/tools/device-link",
    requiresNative: true,
    component: L(() => import("./impl/DeviceLink"), "DeviceLink"),
  },
  {
    id: "field-mapper",
    name: "Field Mapper",
    description: "Map one system's fields onto another's, and see what is not covered",
    category: "healthcare",
    icon: ArrowLeftRight,
    keywords: [
      "map", "mapping", "field", "transform", "crosswalk", "interface", "spec", "hl7", "fhir", "csv", "json",
      "emr", "integration", "coverage", "unmapped", "codegen", "c#",
    ],
    route: "/tools/field-mapper",
    component: L(() => import("./impl/FieldMapper"), "FieldMapper"),
  },
  {
    id: "terminology",
    name: "Terminology Toolkit",
    description: "ICD-10, CPT, LOINC, SNOMED, NDC — structure, check digits and your crosswalk",
    category: "healthcare",
    icon: ScanSearch,
    keywords: [
      "icd", "icd-10", "icd10", "cpt", "hcpcs", "loinc", "snomed", "ndc", "rxnorm", "code", "codes", "coding",
      "terminology", "crosswalk", "check digit", "verhoeff", "diagnosis", "procedure", "vocabulary", "mapping",
    ],
    route: "/tools/terminology",
    component: L(() => import("./impl/TerminologyToolkit"), "TerminologyToolkit"),
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JWT header and claims locally",
    category: "security",
    icon: KeyRound,
    keywords: ["jwt", "token", "decode", "claims", "bearer", "auth"],
    route: "/tools/jwt-decoder",
    component: L(() => import("./impl/JwtDecoder"), "JwtDecoder"),
  },
  {
    id: "guid-generator",
    name: "GUID Generator",
    description: "Generate UUID v4 identifiers",
    category: "quick",
    icon: Fingerprint,
    keywords: ["guid", "uuid", "id", "identifier", "generate", "v4"],
    route: "/tools/guid-generator",
    shortcut: "Ctrl+Shift+G",
    component: L(() => import("./impl/GuidGenerator"), "GuidGenerator"),
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix time and dates",
    category: "quick",
    icon: Clock,
    keywords: ["unix", "timestamp", "epoch", "date", "time", "iso", "utc", "ist", "convert"],
    route: "/tools/unix-timestamp",
    component: L(() => import("./impl/UnixTimestamp"), "UnixTimestamp"),
  },
  {
    id: "base64",
    name: "Base64 Encode / Decode",
    description: "Convert text to and from Base64",
    category: "quick",
    icon: Binary,
    keywords: ["base64", "encode", "decode", "b64"],
    route: "/tools/base64",
    component: L(() => import("./impl/Base64Tool"), "Base64Tool"),
  },
  {
    id: "url-tools",
    name: "URL Encode / Decode",
    description: "Encode/decode URLs and parse query params",
    category: "quick",
    icon: Link2,
    keywords: ["url", "encode", "decode", "query", "params", "uri"],
    route: "/tools/url-tools",
    component: L(() => import("./impl/UrlTools"), "UrlTools"),
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matches",
    category: "quick",
    icon: Regex,
    keywords: ["regex", "regexp", "pattern", "match", "replace", "test"],
    route: "/tools/regex-tester",
    component: L(() => import("./impl/RegexTester"), "RegexTester"),
  },
  {
    id: "docker",
    name: "Docker",
    description: "View and control containers and images",
    category: "devops",
    icon: Container,
    keywords: ["docker", "container", "image", "logs", "compose", "devops"],
    route: "/tools/docker",
    component: L(() => import("./impl/DockerTool"), "DockerTool"),
    requiresNative: true,
  },
  {
    id: "environment-checker",
    name: "Toolchain Manager",
    description: "All dev tools with capabilities, installed version, and one-click install of what is missing",
    category: "devops",
    icon: ListChecks,
    keywords: [
      "environment", "toolchain", "versions", "installed", "install", "winget", "setup", "machine",
      "dotnet", "node", "python", "java", "docker", "git", "sql server", "ssms", "postgres", "redis",
      "rabbitmq", "nats", "elasticsearch", "azure", "aws", "kubectl", "postman", "visual studio",
      "vs code", "cursor", "ollama", "oracle", "dbeaver",
    ],
    route: "/tools/environment-checker",
    component: L(() => import("./impl/EnvironmentChecker"), "EnvironmentChecker"),
    requiresNative: true,
  },
  {
    id: "redis",
    name: "Redis",
    description: "Memory, clients, pub/sub, slow log and keys",
    category: "integration",
    icon: HardDrive,
    keywords: ["redis", "cache", "key", "value", "ttl", "kv", "memory", "pubsub", "clients", "slowlog", "eviction", "info", "scan"],
    route: "/tools/redis",
    component: L(() => import("./impl/RedisTool"), "RedisTool"),
    requiresNative: true,
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    description: "Queues, exchanges, node headroom and publishing (mgmt API)",
    category: "messaging",
    icon: Rabbit,
    keywords: [
      "rabbitmq", "amqp", "queue", "exchange", "message", "broker", "publish", "dlq", "dead letter",
      "unacked", "unacknowledged", "backlog", "consumer", "routing key", "unroutable", "flow control",
      "memory alarm", "vhost", "management",
    ],
    route: "/tools/rabbitmq",
    component: L(() => import("./impl/RabbitMqTool"), "RabbitMqTool"),
  },
  {
    id: "service-bus",
    name: "Azure Service Bus",
    description: "Queues, topics, subscriptions and dead letters (REST + SAS)",
    category: "messaging",
    icon: CloudCog,
    keywords: [
      "azure", "service bus", "servicebus", "asb", "queue", "topic", "subscription", "dead letter", "dlq",
      "deadletterqueue", "peek", "sas", "shared access", "broker", "message", "transfer dlq", "session",
      "max delivery count", "lock", "namespace",
    ],
    route: "/tools/service-bus",
    component: L(() => import("./impl/ServiceBusTool"), "ServiceBusTool"),
  },
  {
    id: "kql-pad",
    name: "KQL Pad",
    description: "Query Log Analytics and App Insights, with the cost mistakes flagged",
    category: "diagnostics",
    icon: CloudCog,
    keywords: [
      "kql", "kusto", "log analytics", "application insights", "app insights", "azure monitor", "logs", "query",
      "workspace", "telemetry", "trace", "apprequests", "appexceptions", "summarize", "render", "timechart",
    ],
    route: "/tools/kql-pad",
    component: L(() => import("./impl/KqlPad"), "KqlPad"),
  },
  {
    id: "nats",
    name: "NATS",
    description: "Server, connections, subjects and JetStream",
    category: "messaging",
    icon: Antenna,
    keywords: ["nats", "jetstream", "subject", "message", "broker", "monitoring", "stream", "consumer", "ack", "pending", "redelivery", "wildcard", "varz", "jsz"],
    route: "/tools/nats",
    component: L(() => import("./impl/NatsTool"), "NatsTool"),
  },
  {
    id: "process-manager",
    name: "Process Manager",
    description: "Search, inspect and kill processes",
    category: "diagnostics",
    icon: Cpu,
    keywords: ["process", "task", "kill", "cpu", "memory", "pid"],
    route: "/tools/process-manager",
    component: L(() => import("./impl/ProcessManager"), "ProcessManager"),
    requiresNative: true,
  },
  {
    id: "network-tools",
    name: "Network Utilities",
    description: "Ping, DNS lookup and TCP checks",
    category: "diagnostics",
    icon: Radio,
    keywords: ["network", "ping", "dns", "tcp", "traceroute", "lookup"],
    route: "/tools/network-tools",
    component: L(() => import("./impl/NetworkTools"), "NetworkTools"),
    requiresNative: true,
  },
  {
    id: "log-viewer",
    name: "Log Viewer",
    description: "Open, filter and search log files",
    category: "diagnostics",
    icon: ScrollText,
    keywords: ["log", "logs", "viewer", "error", "warn", "filter", "search"],
    route: "/tools/log-viewer",
    component: L(() => import("./impl/LogViewer"), "LogViewer"),
  },
  {
    id: "stack-trace-analyzer",
    name: "Stack Trace Analyzer",
    description: "Parse .NET/Java/JS stack traces",
    category: "diagnostics",
    icon: Layers,
    keywords: ["stack", "trace", "exception", "error", "frame", "analyze"],
    route: "/tools/stack-trace-analyzer",
    component: L(() => import("./impl/StackTraceAnalyzer"), "StackTraceAnalyzer"),
  },
  {
    id: "context-pack",
    name: "DevHelper Context Pack",
    description: "Assemble evidence into one AI diagnosis",
    category: "diagnostics",
    icon: PackageSearch,
    keywords: ["context", "diagnose", "root cause", "debug", "analyze everything", "evidence"],
    route: "/tools/context-pack",
    component: L(() => import("./impl/ContextPack"), "ContextPack"),
  },
  {
    id: "phi-gateway",
    name: "PHI Gateway",
    description: "What leaves the machine when an AI tool runs, and what is removed first",
    category: "ai",
    icon: ShieldAlert,
    keywords: [
      "phi", "pii", "hipaa", "safe harbor", "deidentify", "de-identify", "redact", "anonymise", "anonymize",
      "privacy", "patient", "mrn", "aadhaar", "gateway", "ai", "prompt", "leak", "compliance", "mask",
    ],
    route: "/tools/phi-gateway",
    component: L(() => import("./impl/PhiGateway"), "PhiGateway"),
  },
  {
    id: "error-explainer",
    name: "Error Explainer",
    description: "AI root-cause and fix for an error",
    category: "ai",
    icon: Bug,
    keywords: ["error", "explain", "ai", "exception", "fix", "root cause"],
    route: "/tools/error-explainer",
    component: L(() => import("./impl/ErrorExplainer"), "ErrorExplainer"),
  },
  {
    id: "code-explainer",
    name: "Code Explainer",
    description: "AI explanation of a code snippet",
    category: "ai",
    icon: FileSearch,
    keywords: ["code", "explain", "ai", "understand", "walkthrough"],
    route: "/tools/code-explainer",
    component: L(() => import("./impl/CodeExplainer"), "CodeExplainer"),
  },
  {
    id: "api-failure-analyzer",
    name: "API Failure Analyzer",
    description: "AI analysis of a failing API call",
    category: "ai",
    icon: ShieldAlert,
    keywords: ["api", "failure", "analyze", "ai", "500", "error", "debug"],
    route: "/tools/api-failure-analyzer",
    component: L(() => import("./impl/ApiFailureAnalyzer"), "ApiFailureAnalyzer"),
  },
  {
    id: "test-generator",
    name: "Test Case Generator",
    description: "AI test scenarios from code/requirements",
    category: "ai",
    icon: FlaskConical,
    keywords: ["test", "cases", "unit", "generate", "ai", "qa", "scenarios"],
    route: "/tools/test-generator",
    component: L(() => import("./impl/TestGenerator"), "TestGenerator"),
  },
  {
    id: "snippet-library",
    name: "Snippet Library",
    description: "Save and search reusable code snippets",
    category: "snippets",
    icon: Bookmark,
    keywords: ["snippet", "code", "library", "save", "reuse", "tags"],
    route: "/tools/snippet-library",
    component: L(() => import("./impl/SnippetLibrary"), "SnippetLibrary"),
  },
  {
    id: "project-profiles",
    name: "Project Profiles",
    description: "Per-project tech stack and notes",
    category: "projects",
    icon: FolderKanban,
    keywords: ["project", "profile", "stack", "notes", "context"],
    route: "/tools/project-profiles",
    component: L(() => import("./impl/ProjectProfiles"), "ProjectProfiles"),
  },
  {
    id: "port-checker",
    name: "Port Checker",
    description: "Find and free the process on a TCP port",
    category: "diagnostics",
    icon: Network,
    keywords: ["port", "tcp", "kill", "process", "listening", "netstat", "8080"],
    route: "/tools/port-checker",
    shortcut: "Ctrl+Shift+P",
    component: L(() => import("./impl/PortChecker"), "PortChecker"),
    requiresNative: true,
  },
  {
    id: "command-cheatsheet",
    name: "Command Reference",
    description: "Everyday commands for Git, SSH, Linux, Windows, MSSQL, PgSQL, Redis, NATS, cURL, network, .NET & npm",
    category: "commands",
    icon: TerminalSquare,
    keywords: ["command", "cheatsheet", "reference", "git", "ssh", "putty", "linux", "windows", "mssql", "postgres", "pgsql", "redis", "nats", "curl", "network", "dotnet", "npm", "terminal", "bash", "azure", "az cli", "cloud", "aks", "app service", "key vault", "storage"],
    route: "/tools/command-cheatsheet",
    component: L(() => import("./impl/CommandCheatsheet"), "CommandCheatsheet"),
  },
  {
    id: "database-toolkit",
    name: "Database Toolkit",
    description: "Connect to PostgreSQL/MySQL/SQL Server/SQLite, explore objects, run queries with safe-mode, export & generate code",
    category: "database",
    icon: DatabaseIcon,
    keywords: ["database", "db", "sql", "postgres", "postgresql", "mysql", "mariadb", "sqlserver", "mssql", "oracle", "sqlite", "query", "table", "schema", "connection", "explorer"],
    route: "/tools/database-toolkit",
    component: L(() => import("./impl/DatabaseToolkit"), "DatabaseToolkit"),
    requiresNative: true,
  },
  {
    id: "debug-session",
    name: "Debug Session",
    description: "Reconstruct a distributed flow on one timeline — aggregate logs, API calls, DB & messages by correlation/trace id, then diagnose",
    category: "diagnostics",
    icon: BugIcon,
    keywords: [
      "debug", "session", "timeline", "trace", "correlation", "root cause", "diagnose", "incident", "logs",
      "distributed", "flows", "duplicates", "cascade", "capture",
    ],
    route: "/tools/debug-session",
    component: L(() => import("./impl/DebugSession"), "DebugSession"),
  },
  {
    id: "trace-explorer",
    name: "Trace Explorer",
    description: "Enter a correlation/trace/request id and reconstruct its path across every captured source — timeline, service flow, failure point",
    category: "diagnostics",
    icon: RouteIcon,
    keywords: [
      "trace", "correlation", "request id", "explorer", "distributed", "span", "flow", "root cause",
      "opentelemetry", "otel", "waterfall", "latency", "gap", "slow", "bottleneck", "retry",
    ],
    route: "/tools/trace-explorer",
    component: L(() => import("./impl/TraceExplorer"), "TraceExplorer"),
  },
  {
    id: "config-inspector",
    name: "Config Inspector",
    description: "Compare appsettings.json across environments — added/removed/changed keys with automatic secret masking",
    category: "devops",
    icon: FileCog,
    keywords: ["config", "appsettings", "configuration", "dotnet", ".net", "environment", "compare", "diff", "secrets", "json"],
    route: "/tools/config-inspector",
    component: L(() => import("./impl/ConfigInspector"), "ConfigInspector"),
  },
  {
    id: "cron",
    name: "Cron Expression",
    description: "Parse, validate and explain a cron expression; preview the next run times (5- and 6-field)",
    category: "quick",
    icon: CalendarClock,
    keywords: ["cron", "crontab", "schedule", "cronjob", "quartz", "next run", "expression", "timer"],
    route: "/tools/cron",
    component: L(() => import("./impl/CronTool"), "CronTool"),
  },
  {
    id: "star-map",
    name: "Star Map",
    description: "Live map with a simulation lab — race departures against each other, model congestion, and read terrain, geology, sun and weather",
    category: "gadgets",
    icon: MapIcon,
    keywords: [
      "map", "star map", "gps", "location", "navigation", "route", "routing", "directions",
      "waypoint", "gpx", "geojson", "offline", "tiles", "leaflet", "openstreetmap", "osm",
      "trip", "distance", "search", "geocode", "places", "measure", "weather", "radar",
      "simulation", "simulate", "traffic", "congestion", "eta", "departure", "encounter",
      "elevation", "profile", "gradient", "slope", "aspect", "terrain", "hillshade", "contour",
      "geology", "geologist", "bedrock", "macrostrat", "earthquake", "seismic", "usgs",
      "sunrise", "sunset", "golden hour", "moon", "air quality", "aqi", "traveller", "traveler",
    ],
    route: "/tools/star-map",
    component: L(() => import("./impl/StarMap"), "StarMap"),
  },
  {
    id: "notes",
    name: "Notes",
    description: "Markdown notes that link to each other — tags, tasks, backlinks, outline and local history, all read out of the text itself",
    category: "gadgets",
    icon: NotebookPen,
    keywords: [
      "notes", "note", "notepad", "markdown", "md", "scratchpad", "journal", "diary",
      "todo", "to-do", "task", "checklist", "tag", "tags", "wiki", "backlink", "link",
      "zettelkasten", "outline", "template", "daily", "meeting", "decision", "adr",
      "write", "draft", "memo", "history", "revision",
    ],
    route: "/tools/notes",
    component: L(() => import("./impl/Notes"), "Notes"),
  },
];

const TOOL_MAP = new Map(TOOLS.map((t) => [t.id, t]));

export function getTool(id: string): Tool | undefined {
  return TOOL_MAP.get(id);
}

export function toolsByCategory(categoryId: string): Tool[] {
  return TOOLS.filter((t) => t.category === categoryId);
}

/** Fuzzy-ish search over name, description and keywords for the command palette. */
export function searchTools(query: string): Tool[] {
  const q = query.trim().toLowerCase();
  if (!q) return TOOLS;
  const terms = q.split(/\s+/);
  return TOOLS.map((tool) => {
    const haystack = [tool.name, tool.description, ...tool.keywords].join(" ").toLowerCase();
    const score = terms.reduce((acc, term) => (haystack.includes(term) ? acc + 1 : acc), 0);
    return { tool, score };
  })
    .filter((r) => r.score === terms.length)
    .sort((a, b) => a.tool.name.localeCompare(b.tool.name))
    .map((r) => r.tool);
}
